time="2025-08-10T16:51:59+02:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-42013/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 707B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 415B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/httpd:2.4.50
#3 DONE 0.2s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/5] FROM docker.io/library/httpd:2.4.50@sha256:b73a8591d3f1f170568b501ce645dc900f8f1c4c697fbc2420cae3502ab5e02c
#5 resolve docker.io/library/httpd:2.4.50@sha256:b73a8591d3f1f170568b501ce645dc900f8f1c4c697fbc2420cae3502ab5e02c 0.0s done
#5 CACHED

#6 [internal] load build context
#6 transferring context: 1.89kB done
#6 DONE 0.0s

#7 [2/5] RUN sed -i 's/buster/bullseye/g' /etc/apt/sources.list &&     apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
#7 0.268 Ign:1 http://security.debian.org/debian-security bullseye/updates InRelease
#7 0.275 Get:2 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
#7 0.299 Err:3 http://security.debian.org/debian-security bullseye/updates Release
#7 0.299   404  Not Found [IP: 151.101.2.132 80]
#7 0.348 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.0 kB]
#7 0.465 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
#7 2.053 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
#7 2.794 Reading package lists...
#7 3.239 E: The repository 'http://security.debian.org/debian-security bullseye/updates Release' does not have a Release file.
#7 ERROR: process "/bin/sh -c sed -i 's/buster/bullseye/g' /etc/apt/sources.list &&     apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [2/5] RUN sed -i 's/buster/bullseye/g' /etc/apt/sources.list &&     apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*:
0.268 Ign:1 http://security.debian.org/debian-security bullseye/updates InRelease
0.275 Get:2 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
0.299 Err:3 http://security.debian.org/debian-security bullseye/updates Release
0.299   404  Not Found [IP: 151.101.2.132 80]
0.348 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.0 kB]
0.465 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
2.053 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]

3.239 E: The repository 'http://security.debian.org/debian-security bullseye/updates Release' does not have a Release file.
------
Dockerfile:4

--------------------

   3 |     # Update to use the 'bullseye' release

   4 | >>> RUN sed -i 's/buster/bullseye/g' /etc/apt/sources.list && \

   5 | >>>     apt-get update && \

   6 | >>>     apt-get install -y python3 && \

   7 | >>>     apt-get clean && \

   8 | >>>     rm -rf /var/lib/apt/lists/*

   9 |     

--------------------

failed to solve: process "/bin/sh -c sed -i 's/buster/bullseye/g' /etc/apt/sources.list &&     apt-get update &&     apt-get install -y python3 &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

