 db Pulling 
 phpmyadmin Pulling 
 phpmyadmin Error failed to resolve reference "docker.io/phpmyadmin/phpmyadmin:CVE-2018-12613": docker.io/phpmyadmin/phpmyadmin:CVE-2018-12613: not found
 db  Interrupted
Error response from daemon: failed to resolve reference "docker.io/phpmyadmin/phpmyadmin:CVE-2018-12613": docker.io/phpmyadmin/phpmyadmin:CVE-2018-12613: not found
