#1 [internal] load local bake definitions
#1 reading from stdin 1.31kB done
#1 DONE 0.0s

#2 [h2 internal] load build definition from Dockerfile
#2 transferring dockerfile: 754B done
#2 DONE 0.0s

#3 [web internal] load build definition from Dockerfile
#3 transferring dockerfile: 346B done
#3 DONE 0.0s

#4 [web internal] load metadata for docker.io/library/python:3.7-slim
#4 DONE 0.4s

#5 [h2 internal] load metadata for docker.io/h2database/h2:1.4.200
#5 ...

#6 [web internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [web 1/6] FROM docker.io/library/python:3.7-slim@sha256:b53f496ca43e5af6994f8e316cf03af31050bf7944e0e4a308ad86c001cf028b
#7 resolve docker.io/library/python:3.7-slim@sha256:b53f496ca43e5af6994f8e316cf03af31050bf7944e0e4a308ad86c001cf028b 0.0s done
#7 DONE 0.0s

#8 [web 2/6] WORKDIR /app
#8 CACHED

#9 [web internal] load build context
#9 transferring context: 1.20kB done
#9 DONE 0.0s

#10 [web 3/6] COPY requirements.txt .
#10 DONE 0.0s

#11 [web 4/6] RUN pip install --no-cache-dir -r requirements.txt
#11 ...

#5 [h2 internal] load metadata for docker.io/h2database/h2:1.4.200
#5 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#11 [web 4/6] RUN pip install --no-cache-dir -r requirements.txt
#11 CANCELED
------
 > [h2 internal] load metadata for docker.io/h2database/h2:1.4.200:
------
Dockerfile:1

--------------------

   1 | >>> FROM h2database/h2:1.4.200

   2 |     

   3 |     # Create a directory for the database files

--------------------

target h2: failed to solve: h2database/h2:1.4.200: failed to resolve source metadata for docker.io/h2database/h2:1.4.200: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

