#1 [internal] load local bake definitions
#1 reading from stdin 1.44kB done
#1 DONE 0.0s

#2 [hardened-geoserver internal] load build definition from Dockerfile
#2 transferring dockerfile: 341B done
#2 DONE 0.0s

#3 [vulnerable-app internal] load build definition from Dockerfile
#3 transferring dockerfile: 392B done
#3 DONE 0.0s

#4 [vulnerable-app internal] load metadata for docker.io/library/python:3.10-slim
#4 DONE 0.4s

#5 [hardened-geoserver internal] load metadata for docker.io/geoserver/geoserver:2.25.2
#5 ...

#6 [vulnerable-app internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [vulnerable-app internal] load build context
#7 transferring context: 1.94kB done
#7 DONE 0.0s

#8 [vulnerable-app 1/6] FROM docker.io/library/python:3.10-slim@sha256:e0c4fae70d550834a40f6c3e0326e02cfe239c2351d922e1fb1577a3c6ebde02
#8 resolve docker.io/library/python:3.10-slim@sha256:e0c4fae70d550834a40f6c3e0326e02cfe239c2351d922e1fb1577a3c6ebde02 0.0s done
#8 DONE 0.0s

#9 [vulnerable-app 2/6] WORKDIR /app
#9 CACHED

#10 [vulnerable-app 3/6] RUN apt-get update &&     apt-get install -y --no-install-recommends curl &&     rm -rf /var/lib/apt/lists/* &&     pip install --upgrade pip
#10 ...

#5 [hardened-geoserver internal] load metadata for docker.io/geoserver/geoserver:2.25.2
#5 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#10 [vulnerable-app 3/6] RUN apt-get update &&     apt-get install -y --no-install-recommends curl &&     rm -rf /var/lib/apt/lists/* &&     pip install --upgrade pip
#10 CANCELED
------
 > [hardened-geoserver internal] load metadata for docker.io/geoserver/geoserver:2.25.2:
------
Dockerfile:1

--------------------

   1 | >>> FROM geoserver/geoserver:2.25.2

   2 |     # Switch to root to install additional packages

   3 |     USER root

--------------------

target hardened-geoserver: failed to solve: geoserver/geoserver:2.25.2: failed to resolve source metadata for docker.io/geoserver/geoserver:2.25.2: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

