time="2025-10-29T18:15:27+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2023-22527/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 722B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 759B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/atlassian/confluence-server:8.5.3
#3 DONE 0.4s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/5] FROM docker.io/atlassian/confluence-server:8.5.3@sha256:12141c1cb9f5d295a5d15860db3e2e0075520040f9c064cb5f7986d98c6ae81b
#5 resolve docker.io/atlassian/confluence-server:8.5.3@sha256:12141c1cb9f5d295a5d15860db3e2e0075520040f9c064cb5f7986d98c6ae81b 0.0s done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 245B done
#6 DONE 0.0s

#7 [2/5] RUN apt-get update &&     apt-get install -y --no-install-recommends         ca-certificates         wget         unzip         netcat-openbsd &&     rm -rf /var/lib/apt/lists/*
#7 CACHED

#8 [4/5] COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
#8 CACHED

#9 [3/5] RUN chmod +x /opt/atlassian/confluence/bin/start-confluence.sh || true
#9 CACHED

#10 [5/5] RUN chmod +x /usr/local/bin/wait-for-it.sh
#10 CACHED

#11 exporting to image
#11 exporting layers done
#11 exporting manifest sha256:851b8a5e75e39ed684f4aa4ffdd09cdae977b6a9f952b9dba1a1a2c7f2e4db88 done
#11 exporting config sha256:4213cf6a7aa49d2311f4d489f8881bed8be3a6378ff39016b5b698cbd6638422 done
#11 exporting attestation manifest sha256:21f852f727c3f39087d42c2488e7762ec9aad0596bf63c33229bce89212e16db 0.0s done
#11 exporting manifest list sha256:8a28bbdb1c028e98e652ee64df3c1cdcf64e08c35398ad2c23ce5ac468c839ad 0.0s done
#11 naming to docker.io/library/custom-confluence:latest
#11 naming to docker.io/library/custom-confluence:latest done
#11 unpacking to docker.io/library/custom-confluence:latest 0.0s done
#11 DONE 0.1s

#12 resolving provenance for metadata file
#12 DONE 0.0s
 custom-confluence:latest  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Volume custom_no_tool_db_data  Creating
 Volume custom_no_tool_db_data  Created
 Container postgres  Creating
 Container postgres  Created
 Container confluence  Creating
 Container confluence  Created
 Container nginx  Creating
 Container nginx  Created
 Container postgres  Starting
 Container postgres  Started
 Container postgres  Waiting
 Container postgres  Healthy
 Container confluence  Starting
 Container confluence  Started
 Container nginx  Starting
 Container nginx  Started


sudo docker logs 0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9 --details
STDOUT: 
STDERR:  INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'
 INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
 INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
 INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
 Traceback (most recent call last):
   File "/entrypoint.py", line 18, in <module>
     gen_cfg('confluence.cfg.xml.j2', f'{CONFLUENCE_HOME}/confluence.cfg.xml',
   File "/entrypoint_helpers.py", line 66, in gen_cfg
     cfg = jenv.get_template(tmpl).render(env)
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
     self.environment.handle_exception()
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 33, in top-level template code
     <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 455, in getitem
     return obj[argument]
 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'postgres'




sudo docker inspect 0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9[
    {
        "Id": "0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9",
        "Created": "2025-10-29T17:15:28.312668294Z",
        "Path": "/usr/bin/tini",
        "Args": [
            "--",
            "/entrypoint.py"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-29T17:16:02.924813066Z",
            "FinishedAt": "2025-10-29T17:16:03.514245676Z"
        },
        "Image": "sha256:8a28bbdb1c028e98e652ee64df3c1cdcf64e08c35398ad2c23ce5ac468c839ad",
        "ResolvConfPath": "/var/lib/docker/containers/0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9/hostname",
        "HostsPath": "/var/lib/docker/containers/0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9/hosts",
        "LogPath": "/var/lib/docker/containers/0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9/0b926998bcacb36d54063b7a84639e6cc04735eccaf9a008ab62b53f077081d9-json.log",
        "Name": "/confluence",
        "RestartCount": 9,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "8090/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8090"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "6f68f507e8bf5325dce82ce7507932572dac03f81926546282505381b0790dfd",
                "Source": "/var/lib/docker/volumes/6f68f507e8bf5325dce82ce7507932572dac03f81926546282505381b0790dfd/_data",
                "Destination": "/var/atlassian/application-data/confluence",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "0b926998bcac",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "8090/tcp": {},
                "8091/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ATL_DB_TYPE=postgres",
                "ATL_JDBC_URL=jdbc:postgresql://db:5432/confluence",
                "ATL_JDBC_USER=confluence_user",
                "ATL_JDBC_PASSWORD=confluence_pass",
                "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/opt/java/openjdk",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_VERSION=jdk-11.0.21+9",
                "APP_NAME=confluence",
                "RUN_USER=confluence",
                "RUN_GROUP=confluence",
                "RUN_UID=2002",
                "RUN_GID=2002",
                "CONFLUENCE_HOME=/var/atlassian/application-data/confluence",
                "CONFLUENCE_INSTALL_DIR=/opt/atlassian/confluence",
                "CONFLUENCE_LOG_STDOUT=false",
                "CONFLUENCE_VERSION=8.5.3"
            ],
            "Cmd": [
                "/entrypoint.py"
            ],
            "Image": "custom-confluence:latest",
            "Volumes": {
                "/var/atlassian/application-data/confluence": {}
            },
            "WorkingDir": "/var/atlassian/application-data/confluence",
            "Entrypoint": [
                "/usr/bin/tini",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "f554e1bc99ea5e8f3fe0616fcadc697eed5da97143c6868f16672107efcd5327",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "db:service_healthy:false",
                "com.docker.compose.image": "sha256:8a28bbdb1c028e98e652ee64df3c1cdcf64e08c35398ad2c23ce5ac468c839ad",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2023-22527/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2023-22527/custom_no_tool",
                "com.docker.compose.service": "confluence",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu",
                "maintainer": "dc-deployments@atlassian.com",
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "22.04",
                "securitytxt": "https://www.atlassian.com/.well-known/security.txt"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "confluence",
                        "confluence"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "81c4eab40e1d68ef9f8a2f5c0e670436f5215851a03f741e8003826e96251237",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "confluence",
                        "0b926998bcac"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:851b8a5e75e39ed684f4aa4ffdd09cdae977b6a9f952b9dba1a1a2c7f2e4db88",
            "size": 4680,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]