time="2025-08-11T18:59:53+02:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-7247/custom/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 1.31kB done
#1 DONE 0.0s

#2 [opensmtpd internal] load build definition from Dockerfile.opensmtpd
#2 transferring dockerfile: 366B done
#2 DONE 0.0s

#3 [python internal] load build definition from Dockerfile.python
#3 transferring dockerfile: 289B done
#3 DONE 0.0s

#4 [python internal] load metadata for docker.io/library/python:3.8-slim
#4 DONE 1.6s

#5 [opensmtpd internal] load metadata for docker.io/library/debian:buster
#5 DONE 1.8s

#6 [python internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [python 1/2] FROM docker.io/library/python:3.8-slim@sha256:1d52838af602b4b5a831beb13a0e4d073280665ea7be7f69ce2382f29c5a613f
#7 resolve docker.io/library/python:3.8-slim@sha256:1d52838af602b4b5a831beb13a0e4d073280665ea7be7f69ce2382f29c5a613f 0.0s done
#7 ...

#6 [opensmtpd internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#8 [opensmtpd internal] load build context
#8 transferring context: 339B done
#8 DONE 0.0s

#7 [python 1/2] FROM docker.io/library/python:3.8-slim@sha256:1d52838af602b4b5a831beb13a0e4d073280665ea7be7f69ce2382f29c5a613f
#7 sha256:3971691a363796c39467aae4cdce6ef773273fe6bfc67154d01e1b589befb912 0B / 248B 0.3s
#7 sha256:3971691a363796c39467aae4cdce6ef773273fe6bfc67154d01e1b589befb912 248B / 248B 0.4s done
#7 extracting sha256:3971691a363796c39467aae4cdce6ef773273fe6bfc67154d01e1b589befb912 0.0s done
#7 DONE 0.4s

#9 [python 2/2] RUN pip install --no-cache-dir requests
#9 2.536 Collecting requests
#9 2.983   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#9 3.067      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 769.0 kB/s eta 0:00:00
#9 3.234 Collecting certifi>=2017.4.17
#9 3.328   Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
#9 3.510      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.2/161.2 kB 907.7 kB/s eta 0:00:00
#9 3.719 Collecting urllib3<3,>=1.21.1
#9 3.821   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#9 3.968      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 908.0 kB/s eta 0:00:00
#9 4.574 Collecting charset_normalizer<4,>=2
#9 4.670   Downloading charset_normalizer-3.4.3-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (147 kB)
#9 4.813      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 1.1 MB/s eta 0:00:00
#9 4.935 Collecting idna<4,>=2.5
#9 5.014   Downloading idna-3.10-py3-none-any.whl (70 kB)
#9 5.071      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 1.2 MB/s eta 0:00:00
#9 5.147 Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
#9 5.440 Successfully installed certifi-2025.8.3 charset_normalizer-3.4.3 idna-3.10 requests-2.32.4 urllib3-2.2.3
#9 5.440 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 5.944 
#9 5.944 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#9 5.944 [notice] To update, run: pip install --upgrade pip
#9 DONE 6.1s

#10 [python] exporting to image
#10 exporting layers
#10 exporting layers 0.6s done
#10 exporting manifest sha256:52a2bb8f32b78b1fab079709dde68de470b004153f55923f96132de09c1cedae 0.0s done
#10 exporting config sha256:1220505b0875c75ff91bbfc3d1fae63c5b69fc84c21eaa613fac2b65b33049a7 0.0s done
#10 exporting attestation manifest sha256:cbf8147ef7a74e91eabf432bb7b2a821dc2e6620449934044dc41320cc16ce88 0.0s done
#10 exporting manifest list sha256:182a48f698b2ba1d3bd48ff64d41d30367d8466eaa2bc54125dc6a127e87e23e 0.0s done
#10 naming to docker.io/library/python:3.8-CVE-2020-7247
#10 naming to docker.io/library/python:3.8-CVE-2020-7247 done
#10 unpacking to docker.io/library/python:3.8-CVE-2020-7247
#10 unpacking to docker.io/library/python:3.8-CVE-2020-7247 0.3s done
#10 DONE 1.0s

#11 [opensmtpd 1/5] FROM docker.io/library/debian:buster@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225
#11 resolve docker.io/library/debian:buster@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225 0.0s done
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 37.75MB / 50.66MB 7.4s
#11 ...

#12 [python] resolving provenance for metadata file
#12 DONE 0.0s

#11 [opensmtpd 1/5] FROM docker.io/library/debian:buster@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 40.89MB / 50.66MB 8.0s
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 44.04MB / 50.66MB 8.6s
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 47.19MB / 50.66MB 9.2s
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 50.66MB / 50.66MB 9.8s
#11 sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 50.66MB / 50.66MB 9.8s done
#11 extracting sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119
#11 extracting sha256:3892befd2c3f36ceb247ba7d906de12601d69b806597e65c4c837cf3d93df119 1.4s done
#11 DONE 11.3s

#13 [opensmtpd 2/5] RUN apt-get update &&     apt-get install -y opensmtpd=6.6p1-1 &&     rm -rf /var/lib/apt/lists/*
#13 0.359 Ign:1 http://deb.debian.org/debian buster InRelease
#13 0.394 Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
#13 0.436 Ign:3 http://deb.debian.org/debian buster-updates InRelease
#13 0.480 Err:4 http://deb.debian.org/debian buster Release
#13 0.480   404  Not Found [IP: 146.75.54.132 80]
#13 0.523 Err:5 http://deb.debian.org/debian-security buster/updates Release
#13 0.523   404  Not Found [IP: 146.75.54.132 80]
#13 0.565 Err:6 http://deb.debian.org/debian buster-updates Release
#13 0.565   404  Not Found [IP: 146.75.54.132 80]
#13 0.569 Reading package lists...
#13 0.576 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
#13 0.576 E: The repository 'http://deb.debian.org/debian-security buster/updates Release' does not have a Release file.
#13 0.576 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
#13 ERROR: process "/bin/sh -c apt-get update &&     apt-get install -y opensmtpd=6.6p1-1 &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [opensmtpd 2/5] RUN apt-get update &&     apt-get install -y opensmtpd=6.6p1-1 &&     rm -rf /var/lib/apt/lists/*:
0.480 Err:4 http://deb.debian.org/debian buster Release
0.480   404  Not Found [IP: 146.75.54.132 80]
0.523 Err:5 http://deb.debian.org/debian-security buster/updates Release
0.523   404  Not Found [IP: 146.75.54.132 80]
0.565 Err:6 http://deb.debian.org/debian buster-updates Release
0.565   404  Not Found [IP: 146.75.54.132 80]
0.569 Reading package lists...
0.576 E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
0.576 E: The repository 'http://deb.debian.org/debian-security buster/updates Release' does not have a Release file.
0.576 E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
------
Dockerfile.opensmtpd:3

--------------------

   2 |     

   3 | >>> RUN apt-get update && \

   4 | >>>     apt-get install -y opensmtpd=6.6p1-1 && \

   5 | >>>     rm -rf /var/lib/apt/lists/*

   6 |     

--------------------

target opensmtpd: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y opensmtpd=6.6p1-1 &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

