{
  "version": "15.0.6",
  "vulnerabilities": [
    {
      "id": "2c0d3fc544e699f9f79b01ccd7145f09eab77d3acf582d46209f147cf5d7af84",
      "category": "container_scanning",
      "message": "CVE-2021-3487 on alpine/binutils@2.32-r0",
      "cve": "CVE-2021-3487",
      "severity": "Unknown",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/binutils@2.32-r0 to 2.33.1-r1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3487",
          "value": "CVE-2021-3487",
          "url": "https://scout.docker.com/v/CVE-2021-3487?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.33.1-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3487?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.33.1-r1"
        }
      ]
    },
    {
      "id": "a138b0c357b3fbba256e638ea1bbec26799d4f7f2734c26035423d3c973d3246",
      "category": "container_scanning",
      "message": "GHSA-5cpq-8wj7-hf2v on cryptography@2.6.1",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "GHSA-5cpq-8wj7-hf2v",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 41.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-5cpq-8wj7-hf2v",
          "value": "GHSA-5cpq-8wj7-hf2v",
          "url": "https://scout.docker.com/v/GHSA-5cpq-8wj7-hf2v?s=github&n=cryptography&t=pypi&vr=%3E%3D0.5%2C%3C%3D40.0.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-5cpq-8wj7-hf2v?s=github&n=cryptography&t=pypi&vr=%3E%3D0.5%2C%3C%3D40.0.2"
        }
      ]
    },
    {
      "id": "16f6fbd2a1cf15bbd3462a586a7f391ac19ec035bc07ec910e1145cdee727edd",
      "category": "container_scanning",
      "message": "GHSA-jm77-qphf-c4w8 on cryptography@2.6.1",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8-41.0.2 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230731.txt, https://www.openssl.org/news/secadv/20230719.txt, and https://www.openssl.org/news/secadv/20230714.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "GHSA-jm77-qphf-c4w8",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 41.0.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-jm77-qphf-c4w8",
          "value": "GHSA-jm77-qphf-c4w8",
          "url": "https://scout.docker.com/v/GHSA-jm77-qphf-c4w8?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8%2C%3C41.0.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-jm77-qphf-c4w8?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8%2C%3C41.0.3"
        }
      ]
    },
    {
      "id": "f0334c2ffc2980ea572e409b0cee920c7f22826b5a1ffe3bfc95accb40b2826c",
      "category": "container_scanning",
      "message": "GHSA-v8gr-m533-ghj9 on cryptography@2.6.1",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 2.5-41.0.3 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230908.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "GHSA-v8gr-m533-ghj9",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 41.0.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-v8gr-m533-ghj9",
          "value": "GHSA-v8gr-m533-ghj9",
          "url": "https://scout.docker.com/v/GHSA-v8gr-m533-ghj9?s=github&n=cryptography&t=pypi&vr=%3E%3D2.5%2C%3C41.0.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-v8gr-m533-ghj9?s=github&n=cryptography&t=pypi&vr=%3E%3D2.5%2C%3C41.0.4"
        }
      ]
    },
    {
      "id": "322a9702ec79e4879723c998f4f4d483725481fc456d460383156b385b99b6ea",
      "category": "container_scanning",
      "message": "CVE-2021-23839 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2021-23839",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1j-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-23839",
          "value": "CVE-2021-23839",
          "url": "https://scout.docker.com/v/CVE-2021-23839?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-23839?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ]
    },
    {
      "id": "e8011101d8b164abab6f5eaca3cd9459a5ad486a99fcf3df30fadaa627bc6536",
      "category": "container_scanning",
      "message": "CVE-2022-22935 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. A minion authentication denial of service can cause a MiTM attacker to force a minion process to stop by impersonating a master.",
      "cve": "CVE-2022-22935",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22935",
          "value": "CVE-2022-22935",
          "url": "https://scout.docker.com/v/CVE-2022-22935?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22935?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "813b712fd50a27256c3025cbfe9191a5b11b1aa8366d70e3f4cc584f32947527",
      "category": "container_scanning",
      "message": "GHSA-qppv-j76h-2rpx on tornado@4.5.3",
      "description": "## Summary\nTornado interprets `-`, `+`, and `_` in chunk length and `Content-Length` values, which are not allowed by the HTTP RFCs. This can result in request smuggling when Tornado is deployed behind certain proxies that interpret those non-standard characters differently. This is known to apply to older versions of haproxy, although the current release is not affected.\n\n## Details\nTornado uses the `int` constructor to parse the values of `Content-Length` headers and chunk lengths in the following locations:\n### `tornado/http1connection.py:445`\n```python3\n            self._expected_content_remaining = int(headers[\"Content-Length\"])\n```\n### `tornado/http1connection.py:621`\n```python3\n                content_length = int(headers[\"Content-Length\"])  # type: Optional[int]\n```\n### `tornado/http1connection.py:671`\n```python3\n            chunk_len = int(chunk_len_str.strip(), 16)\n```\nBecause `int(\"0_0\") == int(\"+0\") == int(\"-0\") == int(\"0\")`, using the `int` constructor to parse and validate strings that should contain only ASCII digits is not a good strategy. \n\n",
      "cve": "GHSA-qppv-j76h-2rpx",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.3.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-qppv-j76h-2rpx",
          "value": "GHSA-qppv-j76h-2rpx",
          "url": "https://scout.docker.com/v/GHSA-qppv-j76h-2rpx?s=github&n=tornado&t=pypi&vr=%3C6.3.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-qppv-j76h-2rpx?s=github&n=tornado&t=pypi&vr=%3C6.3.3"
        }
      ]
    },
    {
      "id": "5422f1b63f2d6cc0f2feb010559cae42350d00cdfc3b29d471b9804b119d400c",
      "category": "container_scanning",
      "message": "CVE-2023-20898 on salt@2019.2.0",
      "description": "Git Providers can read from the wrong environment because they get the same cache directory base name in Salt masters prior to 3005.2 or 3006.2. Anything that uses Git Providers with different environments can get garbage data or the wrong data, which can lead to wrongful data disclosure, wrongful executions, data corruption and/or crash.",
      "cve": "CVE-2023-20898",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3005.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-20898",
          "value": "CVE-2023-20898",
          "url": "https://scout.docker.com/v/CVE-2023-20898?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-20898?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ]
    },
    {
      "id": "6afce1da2243fe29fec135db95119ff0107215357a345bc696d6563196871041",
      "category": "container_scanning",
      "message": "CVE-2021-25284 on salt@2019.2.0",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. `salt.modules.cmdmod` can log credentials to the info or error log level.",
      "cve": "CVE-2021-25284",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25284",
          "value": "CVE-2021-25284",
          "url": "https://scout.docker.com/v/CVE-2021-25284?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25284?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "17b3090877f2966b51421744c8d44e14990e137b0579d42c8be6718a951d35ce",
      "category": "container_scanning",
      "message": "CVE-2024-37891 on urllib3@1.25.6",
      "description": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
      "cve": "CVE-2024-37891",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.26.19",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-37891",
          "value": "CVE-2024-37891",
          "url": "https://scout.docker.com/v/CVE-2024-37891?s=github&n=urllib3&t=pypi&vr=%3C1.26.19"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-37891?s=github&n=urllib3&t=pypi&vr=%3C1.26.19"
        }
      ]
    },
    {
      "id": "4a8b284c0704fc2585686b8d73ab20fe8e8ad5bfa1eb3d9d316574ce957ea780",
      "category": "container_scanning",
      "message": "CVE-2024-22231 on salt@2019.2.0",
      "description": "Syndic cache directory creation is vulnerable to a directory traversal attack in salt project which can lead a malicious attacker to create an arbitrary directory on a Salt master.",
      "cve": "CVE-2024-22231",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3005.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22231",
          "value": "CVE-2024-22231",
          "url": "https://scout.docker.com/v/CVE-2024-22231?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22231?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ]
    },
    {
      "id": "6af80a652f84c88d80703bda3c994b0f56d94c94dcbbf34a2d2dd45a652a0046",
      "category": "container_scanning",
      "message": "CVE-2019-1551 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2019-1551",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1d-r2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-1551",
          "value": "CVE-2019-1551",
          "url": "https://scout.docker.com/v/CVE-2019-1551?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1d-r2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-1551?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1d-r2"
        }
      ]
    },
    {
      "id": "c172b3c054e230124acf3c4054750c5b190708d89e23b2ddd6280bd6f4d509d1",
      "category": "container_scanning",
      "message": "CVE-2023-20897 on salt@2019.2.0",
      "description": "Salt masters prior to 3005.2 or 3006.2 contain a DOS in minion return. After receiving several bad packets on the request server equal to the number of worker threads, the master will become unresponsive to return requests until restarted.",
      "cve": "CVE-2023-20897",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3005.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-20897",
          "value": "CVE-2023-20897",
          "url": "https://scout.docker.com/v/CVE-2023-20897?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-20897?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ]
    },
    {
      "id": "0c559f03b6bc6b4fc7bb7513beb4f3ad11e28325b0a5a4f08bc30059c07cddee",
      "category": "container_scanning",
      "message": "CVE-2023-28370 on tornado@4.5.3",
      "description": "Open redirect vulnerability in Tornado versions 6.3.1 and earlier allows a remote unauthenticated attacker to redirect a user to an arbitrary web site and conduct a phishing attack by having user access a specially crafted URL.",
      "cve": "CVE-2023-28370",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.3.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-28370",
          "value": "CVE-2023-28370",
          "url": "https://scout.docker.com/v/CVE-2023-28370?s=github&n=tornado&t=pypi&vr=%3C6.3.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-28370?s=github&n=tornado&t=pypi&vr=%3C6.3.2"
        }
      ]
    },
    {
      "id": "261b287e5f37e91e94e954c94738293790c6e715af61a17bc8b701e57f56839b",
      "category": "container_scanning",
      "message": "CVE-2024-47081 on requests@2.22.0",
      "description": "### Impact\n\nDue to a URL parsing issue, Requests releases prior to 2.32.4 may leak .netrc credentials to third parties for specific maliciously-crafted URLs.\n\n### Workarounds\nFor older versions of Requests, use of the .netrc file can be disabled with `trust_env=False` on your Requests Session ([docs](https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env)).\n\n### References\nhttps://github.com/psf/requests/pull/6965\nhttps://seclists.org/fulldisclosure/2025/Jun/2",
      "cve": "CVE-2024-47081",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.22.0 to 2.32.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.22.0"
          },
          "version": "2.22.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-47081",
          "value": "CVE-2024-47081",
          "url": "https://scout.docker.com/v/CVE-2024-47081?s=github&n=requests&t=pypi&vr=%3C2.32.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-47081?s=github&n=requests&t=pypi&vr=%3C2.32.4"
        }
      ]
    },
    {
      "id": "80dbeaff1f39c439c6ee3fd0b72646c6a04b81b39dc07de9fa7683785c0e4df1",
      "category": "container_scanning",
      "message": "CVE-2025-50181 on urllib3@1.25.6",
      "description": "urllib3 handles redirects and retries using the same mechanism, which is controlled by the `Retry` object. The most common way to disable redirects is at the request level, as follows:\n\n```python\nresp = urllib3.request(\"GET\", \"https://httpbin.org/redirect/1\", redirect=False)\nprint(resp.status)\n# 302\n```\n\nHowever, it is also possible to disable redirects, for all requests, by instantiating a `PoolManager` and specifying `retries` in a way that disable redirects:\n\n```python\nimport urllib3\n\nhttp = urllib3.PoolManager(retries=0)  # should raise MaxRetryError on redirect\nhttp = urllib3.PoolManager(retries=urllib3.Retry(redirect=0))  # equivalent to the above\nhttp = urllib3.PoolManager(retries=False)  # should return the first response\n\nresp = http.request(\"GET\", \"https://httpbin.org/redirect/1\")\n```\n\nHowever, the `retries` parameter is currently ignored, which means all the above examples don't disable redirects.\n\n## Affected usages\n\nPassing `retries` on `PoolManager` instantiation to disable redirects or restrict their number.\n\nBy default, requests and botocore users are not affected.\n\n## Impact\n\nRedirects are often used to exploit SSRF vulnerabilities. An application attempting to mitigate SSRF or open redirect vulnerabilities by disabling redirects at the PoolManager level will remain vulnerable.\n\n## Remediation\n\nYou can remediate this vulnerability with the following steps:\n\n * Upgrade to a patched version of urllib3. If your organization would benefit from the continued support of urllib3 1.x, please contact [sethmichaellarson@gmail.com](mailto:sethmichaellarson@gmail.com) to discuss sponsorship or contribution opportunities.\n * Disable redirects at the `request()` level instead of the `PoolManager()` level.",
      "cve": "CVE-2025-50181",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 2.5.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-50181",
          "value": "CVE-2025-50181",
          "url": "https://scout.docker.com/v/CVE-2025-50181?s=github&n=urllib3&t=pypi&vr=%3C2.5.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-50181?s=github&n=urllib3&t=pypi&vr=%3C2.5.0"
        }
      ]
    },
    {
      "id": "96552d085768d3b532db3952a42897aa1566ec2ecf7885cd1828db1892b9a08a",
      "category": "container_scanning",
      "message": "GHSA-753j-mpmx-qq6g on tornado@4.5.3",
      "description": "### Summary\nWhen Tornado receives a request with two `Transfer-Encoding: chunked` headers, it ignores them both. This enables request smuggling when Tornado is deployed behind a proxy server that emits such requests. [Pound](https://en.wikipedia.org/wiki/Pound_(networking)) does this.\n\n### PoC\n0. Install Tornado.\n1. Start a simple Tornado server that echoes each received request's body:\n```bash\ncat << EOF > server.py\nimport asyncio\nimport tornado\n\nclass MainHandler(tornado.web.RequestHandler):\n    def post(self):\n        self.write(self.request.body)\n\nasync def main():\n    tornado.web.Application([(r\"/\", MainHandler)]).listen(8000)\n    await asyncio.Event().wait()\n\nasyncio.run(main())\nEOF\npython3 server.py &\n```\n2. Send a valid chunked request:\n```bash\nprintf 'POST / HTTP/1.1\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n1\\r\\nZ\\r\\n0\\r\\n\\r\\n' | nc localhost 8000\n```\n3. Observe that the response is as expected:\n```\nHTTP/1.1 200 OK\nServer: TornadoServer/6.3.3\nContent-Type: text/html; charset=UTF-8\nDate: Sat, 07 Oct 2023 17:32:05 GMT\nContent-Length: 1\n\nZ\n```\n4. Send a request with two `Transfer-Encoding: chunked` headers:\n```\nprintf 'POST / HTTP/1.1\\r\\nTransfer-Encoding: chunked\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n1\\r\\nZ\\r\\n0\\r\\n\\r\\n' | nc localhost 8000\n```\n5. Observe the strange response:\n```\nHTTP/1.1 200 OK\nServer: TornadoServer/6.3.3\nContent-Type: text/html; charset=UTF-8\nDate: Sat, 07 Oct 2023 17:35:40 GMT\nContent-Length: 0\n\nHTTP/1.1 400 Bad Request\n\n```\nThis is because Tornado believes that the request has no message body, so it tries to interpret `1\\r\\nZ\\r\\n0\\r\\n\\r\\n` as its own request, which causes a 400 response. With a little cleverness involving `chunk-ext`s, you can get Tornado to instead respond 405, which has the potential to desynchronize the connection, as opposed to 400 which should always result in a connection closure.\n\n### Impact\nAnyone using Tornado behind a proxy that forwards requests containing multiple `Transfer-Encoding: chunked` headers is vulnerable to request smuggling, which may entail ACL bypass, cache poisoning, or connection desynchronization.\n",
      "cve": "GHSA-753j-mpmx-qq6g",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.4.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-753j-mpmx-qq6g",
          "value": "GHSA-753j-mpmx-qq6g",
          "url": "https://scout.docker.com/v/GHSA-753j-mpmx-qq6g?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-753j-mpmx-qq6g?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ]
    },
    {
      "id": "7cbcb2eb5d32edf8a29f0971c8f5c78601c1df856676ed1c91ceac35de74c57b",
      "category": "container_scanning",
      "message": "CVE-2024-22195 on jinja2@2.10.1",
      "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing spaces. XML/HTML attributes cannot contain spaces, as each would then be interpreted as a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. Note that accepting keys as user input is not common or a particularly intended use case of the `xmlattr` filter, and an application doing so should already be verifying what keys are provided regardless of this fix.",
      "cve": "CVE-2024-22195",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.10.1 to 3.1.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.10.1"
          },
          "version": "2.10.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22195",
          "value": "CVE-2024-22195",
          "url": "https://scout.docker.com/v/CVE-2024-22195?s=github&n=jinja2&t=pypi&vr=%3C3.1.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22195?s=github&n=jinja2&t=pypi&vr=%3C3.1.3"
        }
      ]
    },
    {
      "id": "f5453b5be5304f64ec53fd9a2f678e06d1c45e44c7969484b0fef9d86d8de54d",
      "category": "container_scanning",
      "message": "CVE-2024-34064 on jinja2@2.10.1",
      "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.",
      "cve": "CVE-2024-34064",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.10.1 to 3.1.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.10.1"
          },
          "version": "2.10.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-34064",
          "value": "CVE-2024-34064",
          "url": "https://scout.docker.com/v/CVE-2024-34064?s=github&n=jinja2&t=pypi&vr=%3C3.1.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-34064?s=github&n=jinja2&t=pypi&vr=%3C3.1.4"
        }
      ]
    },
    {
      "id": "ea48eabb9fe2b343286a67945d4e9ce6b0f6d82b52057cc046f2ee7f88b56155",
      "category": "container_scanning",
      "message": "CVE-2024-56326 on jinja2@2.10.1",
      "description": "An oversight in how the Jinja sandboxed environment detects calls to `str.format` allows an attacker that controls the content of a template to execute arbitrary Python code.\n\nTo exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates.\n\nJinja's sandbox does catch calls to `str.format` and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's `format` method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox.",
      "cve": "CVE-2024-56326",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.10.1 to 3.1.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.10.1"
          },
          "version": "2.10.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-56326",
          "value": "CVE-2024-56326",
          "url": "https://scout.docker.com/v/CVE-2024-56326?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-56326?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.4"
        }
      ]
    },
    {
      "id": "674256e89d9c5aafab8160ba42e2ebc2dece92cf22364e868ce72c5e0bd6d9b2",
      "category": "container_scanning",
      "message": "CVE-2025-27516 on jinja2@2.10.1",
      "description": "An oversight in how the Jinja sandboxed environment interacts with the `|attr` filter allows an attacker that controls the content of a template to execute arbitrary Python code.\n\nTo exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates.\n\nJinja's sandbox does catch calls to `str.format` and ensures they don't escape the sandbox. However, it's possible to use the `|attr` filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the `|attr` filter no longer bypasses the environment's attribute lookup.",
      "cve": "CVE-2025-27516",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.10.1 to 3.1.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.10.1"
          },
          "version": "2.10.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-27516",
          "value": "CVE-2025-27516",
          "url": "https://scout.docker.com/v/CVE-2025-27516?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-27516?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.5"
        }
      ]
    },
    {
      "id": "30ee5e313ae5a8e033fbd1ceb3810cef4a31d539fa436b2a277edb3330b2c628",
      "category": "container_scanning",
      "message": "CVE-2020-13434 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-13434",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-13434",
          "value": "CVE-2020-13434",
          "url": "https://scout.docker.com/v/CVE-2020-13434?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-13434?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "ccfc076a1fb6935c4d97a53d503498ba7d03227e9dadf0d340ab567ef05e83b6",
      "category": "container_scanning",
      "message": "CVE-2020-13435 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-13435",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-13435",
          "value": "CVE-2020-13435",
          "url": "https://scout.docker.com/v/CVE-2020-13435?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-13435?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "c94e5c764c96a2f8028b86c364cbe03689788c56fb7d90d6edac1a629b71cc89",
      "category": "container_scanning",
      "message": "CVE-2020-13631 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-13631",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-13631",
          "value": "CVE-2020-13631",
          "url": "https://scout.docker.com/v/CVE-2020-13631?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-13631?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "56e4915fe68afffc1f0b1e81076a457c54e9beb15c078838136f8f152e6a72ce",
      "category": "container_scanning",
      "message": "CVE-2020-13632 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-13632",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-13632",
          "value": "CVE-2020-13632",
          "url": "https://scout.docker.com/v/CVE-2020-13632?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-13632?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "8753fbb177a2b54edefe3e79d8db3d8c7ab55bdf2dcc2bf669116511649811f6",
      "category": "container_scanning",
      "message": "CVE-2020-15358 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-15358",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-15358",
          "value": "CVE-2020-15358",
          "url": "https://scout.docker.com/v/CVE-2020-15358?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-15358?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "e12a1da2551f3bcda5929dca5b71139d5754390aa5230f4d464173613bb21df7",
      "category": "container_scanning",
      "message": "CVE-2020-17490 on salt@2019.2.0",
      "description": "The TLS module within SaltStack Salt through 3002 creates certificates with weak file permissions.",
      "cve": "CVE-2020-17490",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-17490",
          "value": "CVE-2020-17490",
          "url": "https://scout.docker.com/v/CVE-2020-17490?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-17490?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ]
    },
    {
      "id": "0ea9bb90827851674f08e91dc1b5e9f8ebbd820c457b4189952bbc8795777340",
      "category": "container_scanning",
      "message": "CVE-2020-28928 on alpine/musl@1.1.22-r3",
      "cve": "CVE-2020-28928",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/musl@1.1.22-r3 to 1.1.22-r4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/musl@1.1.22-r3?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.22-r3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28928",
          "value": "CVE-2020-28928",
          "url": "https://scout.docker.com/v/CVE-2020-28928?s=alpine&n=musl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.22-r4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28928?s=alpine&n=musl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.22-r4"
        }
      ]
    },
    {
      "id": "41dbab83ec643c9d87669ee453658ae8153ef9eb28c4890e3ea00b8edc0701b4",
      "category": "container_scanning",
      "message": "CVE-2020-35493 on alpine/binutils@2.32-r0",
      "cve": "CVE-2020-35493",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35493",
          "value": "CVE-2020-35493",
          "url": "https://scout.docker.com/v/CVE-2020-35493?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35493?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "60f775b371b74f7de72324692c7ca263790263b1e1bc17719d3b7ce9ec028258",
      "category": "container_scanning",
      "message": "CVE-2020-35495 on alpine/binutils@2.32-r0",
      "cve": "CVE-2020-35495",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35495",
          "value": "CVE-2020-35495",
          "url": "https://scout.docker.com/v/CVE-2020-35495?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35495?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "7537b3870ca8e71f6b3ef9e77e1700aa6a3a9f6c8171136155f3f5cac9c89164",
      "category": "container_scanning",
      "message": "CVE-2020-35496 on alpine/binutils@2.32-r0",
      "cve": "CVE-2020-35496",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35496",
          "value": "CVE-2020-35496",
          "url": "https://scout.docker.com/v/CVE-2020-35496?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35496?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "d7d8b609d1b7a1e04e8e3bedc6c9fa6cecbf947fac8e8536b0c0f7a0335e4919",
      "category": "container_scanning",
      "message": "CVE-2020-35507 on alpine/binutils@2.32-r0",
      "cve": "CVE-2020-35507",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35507",
          "value": "CVE-2020-35507",
          "url": "https://scout.docker.com/v/CVE-2020-35507?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35507?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "e0965d4e61eb8266dc4fcc7d99d89210fe94a3a2ce4b4ecb01a0afb76b7c884b",
      "category": "container_scanning",
      "message": "CVE-2020-8315 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2020-8315",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.7-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-8315",
          "value": "CVE-2020-8315",
          "url": "https://scout.docker.com/v/CVE-2020-8315?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-8315?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r0"
        }
      ]
    },
    {
      "id": "811ccffc8edb096e259d147d332068fc3c5a6dbf761e8b9468fd5a0d58c30849",
      "category": "container_scanning",
      "message": "CVE-2021-20227 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2021-20227",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-20227",
          "value": "CVE-2021-20227",
          "url": "https://scout.docker.com/v/CVE-2021-20227?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-20227?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "1d738473a87bc5feb3cf6ea0948c0060873ef88e7b78ff5bcd120e3a58d0079d",
      "category": "container_scanning",
      "message": "CVE-2024-0727 on cryptography@2.6.1",
      "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
      "cve": "CVE-2024-0727",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 42.0.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-0727",
          "value": "CVE-2024-0727",
          "url": "https://scout.docker.com/v/CVE-2024-0727?s=github&n=cryptography&t=pypi&vr=%3C42.0.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-0727?s=github&n=cryptography&t=pypi&vr=%3C42.0.2"
        }
      ]
    },
    {
      "id": "1c72dd9ba97c9c24b3fc4854bdf9d32dc53260b7e63abe36fd605a217265578e",
      "category": "container_scanning",
      "message": "CVE-2024-35195 on requests@2.22.0",
      "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
      "cve": "CVE-2024-35195",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.22.0 to 2.32.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.22.0"
          },
          "version": "2.22.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-35195",
          "value": "CVE-2024-35195",
          "url": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0"
        }
      ]
    },
    {
      "id": "35165b72d3596528097d83433750d9370c5224ed1a2517aa0ce31805598d1e02",
      "category": "container_scanning",
      "message": "CVE-2023-45803 on urllib3@1.25.6",
      "description": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.",
      "cve": "CVE-2023-45803",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.26.18",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-45803",
          "value": "CVE-2023-45803",
          "url": "https://scout.docker.com/v/CVE-2023-45803?s=github&n=urllib3&t=pypi&vr=%3C1.26.18"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-45803?s=github&n=urllib3&t=pypi&vr=%3C1.26.18"
        }
      ]
    },
    {
      "id": "531249d4071fe63a251b4247212254432ab64f0510176bb6aaaff89822c3c738",
      "category": "container_scanning",
      "message": "CVE-2019-19242 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2019-19242",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/sqlite@3.28.0-r0 to 3.28.0-r2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-19242",
          "value": "CVE-2019-19242",
          "url": "https://scout.docker.com/v/CVE-2019-19242?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-19242?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r2"
        }
      ]
    },
    {
      "id": "27f774b2294d7bd8ce40d4541979d0ec023bb41f6992bbb99b7de472875d178f",
      "category": "container_scanning",
      "message": "CVE-2020-14422 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2020-14422",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.7-r1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-14422",
          "value": "CVE-2020-14422",
          "url": "https://scout.docker.com/v/CVE-2020-14422?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-14422?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r1"
        }
      ]
    },
    {
      "id": "4d55f268f9a14b1c4ae6a7fc51d2e61f02a2f1e716d7cc033738bbee6250d07f",
      "category": "container_scanning",
      "message": "CVE-2020-1971 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2020-1971",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1i-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-1971",
          "value": "CVE-2020-1971",
          "url": "https://scout.docker.com/v/CVE-2020-1971?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1i-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-1971?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1i-r0"
        }
      ]
    },
    {
      "id": "82a3835aa91781998c048c0c93bf3395600a8abaff6fc5d90933e3265abebf4d",
      "category": "container_scanning",
      "message": "CVE-2021-23841 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2021-23841",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1j-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-23841",
          "value": "CVE-2021-23841",
          "url": "https://scout.docker.com/v/CVE-2021-23841?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-23841?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ]
    },
    {
      "id": "f7af345670a81f1688d0a565e4a557b613a7e64bce64ba1394983f329c084a46",
      "category": "container_scanning",
      "message": "CVE-2021-3449 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2021-3449",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1k-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3449",
          "value": "CVE-2021-3449",
          "url": "https://scout.docker.com/v/CVE-2021-3449?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1k-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3449?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1k-r0"
        }
      ]
    },
    {
      "id": "c315ab9622f7a82811311cfea458c091d01a08760e1a5bbee8a3f3a568e3b4b4",
      "category": "container_scanning",
      "message": "CVE-2022-23491 on certifi@2019.9.11",
      "description": "Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nTrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ).",
      "cve": "CVE-2022-23491",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade certifi@2019.9.11 to 2022.12.07",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/certifi@2019.9.11"
          },
          "version": "2019.9.11"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-23491",
          "value": "CVE-2022-23491",
          "url": "https://scout.docker.com/v/CVE-2022-23491?s=github&n=certifi&t=pypi&vr=%3E%3D2017.11.05%2C%3C2022.12.07"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-23491?s=github&n=certifi&t=pypi&vr=%3E%3D2017.11.05%2C%3C2022.12.07"
        }
      ]
    },
    {
      "id": "aeb5f6810e3a0f2729c23ec17bbefe2c476afce0098cad913c70af5826b8cf2a",
      "category": "container_scanning",
      "message": "CVE-2025-8869 on pip@19.0.3",
      "description": "### Summary\n\nIn the fallback extraction path for source distributions, `pip` used Python’s `tarfile` module without verifying that symbolic/hard link targets resolve inside the intended extraction directory. A malicious sdist can include links that escape the target directory and overwrite arbitrary files on the invoking host during `pip install`.\n\n### Impact\n\nSuccessful exploitation enables arbitrary file overwrite outside the build/extraction directory on the machine running `pip`. This can be leveraged to tamper with configuration or startup files and may lead to further code execution depending on the environment, but the direct, guaranteed impact is integrity compromise on the vulnerable system.\n\n### Conditions\n\nThe issue is triggered when installing an attacker-controlled sdist (e.g., from an index or URL) and the fallback extraction code path is used. No special privileges are required beyond running `pip install`; active user action is necessary.\n\n### Remediation\n\nThe [fix](https://github.com/pypa/pip/pull/13550), while available as a patch that can be manually applied, has not yet been put into a numbered version but is planned for `25.3`. Using a Python interpreter that implements the safe-extraction behavior described by **PEP 706** provides additional defense in depth for other `tarfile` issues but is not a substitute for upgrading pip for this specific flaw.",
      "cve": "CVE-2025-8869",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@19.0.3"
          },
          "version": "19.0.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-8869",
          "value": "CVE-2025-8869",
          "url": "https://scout.docker.com/v/CVE-2025-8869?s=github&n=pip&t=pypi&vr=%3C%3D25.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-8869?s=github&n=pip&t=pypi&vr=%3C%3D25.2"
        }
      ]
    },
    {
      "id": "16d18a3342bf74bf56cf4a403d95320ec2659bf047a07df01c44bf4f50627989",
      "category": "container_scanning",
      "message": "CVE-2019-16935 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2019-16935",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.5-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-16935",
          "value": "CVE-2019-16935",
          "url": "https://scout.docker.com/v/CVE-2019-16935?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.5-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-16935?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.5-r0"
        }
      ]
    },
    {
      "id": "d12f050cd78939dea49f242c3927a9d7b9e0a8d0a446066d047e5ae536f03ce0",
      "category": "container_scanning",
      "message": "CVE-2020-35494 on alpine/binutils@2.32-r0",
      "cve": "CVE-2020-35494",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35494",
          "value": "CVE-2020-35494",
          "url": "https://scout.docker.com/v/CVE-2020-35494?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35494?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "8a8e26ab6597437dc2dae693c39c8ef787edba11b0939e1c1218c97269386f33",
      "category": "container_scanning",
      "message": "CVE-2023-32681 on requests@2.22.0",
      "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
      "cve": "CVE-2023-32681",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.22.0 to 2.31.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.22.0"
          },
          "version": "2.22.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-32681",
          "value": "CVE-2023-32681",
          "url": "https://scout.docker.com/v/CVE-2023-32681?s=github&n=requests&t=pypi&vr=%3E%3D2.3.0%2C%3C2.31.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-32681?s=github&n=requests&t=pypi&vr=%3E%3D2.3.0%2C%3C2.31.0"
        }
      ]
    },
    {
      "id": "2362fb95a74d09c2dea77c6b251d8474d5df842d3b7438c392ed696c20dcb32e",
      "category": "container_scanning",
      "message": "CVE-2021-20197 on alpine/binutils@2.32-r0",
      "cve": "CVE-2021-20197",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-20197",
          "value": "CVE-2021-20197",
          "url": "https://scout.docker.com/v/CVE-2021-20197?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-20197?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "c3b930b213f97a392b769f7e6eacba3ce72efee79f42fc0022eb0a47ab22adf3",
      "category": "container_scanning",
      "message": "CVE-2019-16168 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2019-16168",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/sqlite@3.28.0-r0 to 3.28.0-r1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-16168",
          "value": "CVE-2019-16168",
          "url": "https://scout.docker.com/v/CVE-2019-16168?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-16168?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r1"
        }
      ]
    },
    {
      "id": "86d468b68b540c79ef6d7d60c187bac1af6c0a1f219edac50f4404eadbbd240b",
      "category": "container_scanning",
      "message": "CVE-2020-8492 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2020-8492",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.7-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-8492",
          "value": "CVE-2020-8492",
          "url": "https://scout.docker.com/v/CVE-2020-8492?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-8492?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r0"
        }
      ]
    },
    {
      "id": "5cce251ba6db7b89fd764bd64124ff9c85c641a13f3bfde08e553ffd2349e630",
      "category": "container_scanning",
      "message": "GHSA-w235-7p84-xx57 on tornado@4.5.3",
      "description": "### Summary\nTornado’s `curl_httpclient.CurlAsyncHTTPClient` class is vulnerable to CRLF (carriage return/line feed) injection in the request headers.\n\n### Details\nWhen an HTTP request is sent using `CurlAsyncHTTPClient`, Tornado does not reject carriage return (\\r) or line feed (\\n) characters in the request headers. As a result, if an application includes an attacker-controlled header value in a request sent using `CurlAsyncHTTPClient`, the attacker can inject arbitrary headers into the request or cause the application to send arbitrary requests to the specified server.\n\nThis behavior differs from that of the standard `AsyncHTTPClient` class, which does reject CRLF characters.\n\nThis issue appears to stem from libcurl's (as well as pycurl's) lack of validation for the [`HTTPHEADER`](https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html) option. libcurl’s documentation states:\n\n> The headers included in the linked list must not be CRLF-terminated, because libcurl adds CRLF after each header item itself. Failure to comply with this might result in strange behavior. libcurl passes on the verbatim strings you give it, without any filter or other safe guards. That includes white space and control characters.\n\npycurl similarly appears to assume that the headers adhere to the correct format. Therefore, without any validation on Tornado’s part, header names and values are included verbatim in the request sent by `CurlAsyncHTTPClient`, including any control characters that have special meaning in HTTP semantics.\n\n### PoC\nThe issue can be reproduced using the following script:\n\n```python\nimport asyncio\n\nfrom tornado import httpclient\nfrom tornado import curl_httpclient\n\nasync def main():\n    http_client = curl_httpclient.CurlAsyncHTTPClient()\n\n    request = httpclient.HTTPRequest(\n        # Burp Collaborator payload\n        \"http://727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com/\",\n        method=\"POST\",\n        body=\"body\",\n        # Injected header using CRLF characters\n        headers={\"Foo\": \"Bar\\r\\nHeader: Injected\"}\n    )\n\n    response = await http_client.fetch(request)\n    print(response.body)\n\n    http_client.close()\n\nif __name__ == \"__main__\":\n    asyncio.run(main())\n```\n\nWhen the specified server receives the request, it contains the injected header (`Header: Injected`) on its own line:\n\n```http\nPOST / HTTP/1.1\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com\nUser-Agent: Mozilla/5.0 (compatible; pycurl)\nAccept: */*\nAccept-Encoding: gzip,deflate\nFoo: Bar\nHeader: Injected\nContent-Length: 4\nContent-Type: application/x-www-form-urlencoded\n\nbody\n```\n\nThe attacker can also construct entirely new requests using a payload with multiple CRLF sequences. For example, specifying a header value of `\\r\\n\\r\\nPOST /attacker-controlled-url HTTP/1.1\\r\\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com` results in the server receiving an additional, attacker-controlled request:\n\n```http\nPOST /attacker-controlled-url HTTP/1.1\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com\nContent-Length: 4\nContent-Type: application/x-www-form-urlencoded\n\nbody\n```\n\n### Impact\nApplications using the Tornado library to send HTTP requests with untrusted header data are affected. This issue may facilitate the exploitation of server-side request forgery (SSRF) vulnerabilities.",
      "cve": "GHSA-w235-7p84-xx57",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.4.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-w235-7p84-xx57",
          "value": "GHSA-w235-7p84-xx57",
          "url": "https://scout.docker.com/v/GHSA-w235-7p84-xx57?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-w235-7p84-xx57?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ]
    },
    {
      "id": "9045ae9279924b8dfa0fbbdab30c1ab95216c5de2acab36d2dd54d4f315bd2e4",
      "category": "container_scanning",
      "message": "CVE-2023-34049 on salt@2019.2.0",
      "description": "The Salt-SSH pre-flight option copies the script to the target at a predictable path, which allows an attacker to force Salt-SSH to run their script. If an attacker has access to the target VM and knows the path to the pre-flight script before it runs they can ensure Salt-SSH runs their script with the privileges of the user running Salt-SSH. Do not make the copy path on the target predictable and ensure we check return codes of the scp command if the copy fails.",
      "cve": "CVE-2023-34049",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3005.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-34049",
          "value": "CVE-2023-34049",
          "url": "https://scout.docker.com/v/CVE-2023-34049?s=github&n=salt&t=pypi&vr=%3C3005.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-34049?s=github&n=salt&t=pypi&vr=%3C3005.4"
        }
      ]
    },
    {
      "id": "282057d591758195086752861a7ef9f55236aed7ae5b9803a5626c60b23a7efc",
      "category": "container_scanning",
      "message": "CVE-2023-5752 on pip@19.0.3",
      "description": "When installing a package from a Mercurial VCS URL, e.g. `pip install hg+...`, with pip prior to v23.3, the specified Mercurial revision could be used to inject arbitrary configuration options to the `hg clone` call (e.g. `--config`). Controlling the Mercurial configuration can modify how and which repository is installed. This vulnerability does not affect users who aren't installing from Mercurial.",
      "cve": "CVE-2023-5752",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade pip@19.0.3 to 23.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@19.0.3"
          },
          "version": "19.0.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-5752",
          "value": "CVE-2023-5752",
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ]
    },
    {
      "id": "140b52afafd82a4f8e24dc5e7225ead541bdbde6a16885572e38e636cbd5d1a8",
      "category": "container_scanning",
      "message": "CVE-2020-26137 on urllib3@1.25.6",
      "description": "urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of `putrequest()`. NOTE: this is similar to CVE-2020-26116.",
      "cve": "CVE-2020-26137",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.25.9",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-26137",
          "value": "CVE-2020-26137",
          "url": "https://scout.docker.com/v/CVE-2020-26137?s=github&n=urllib3&t=pypi&vr=%3C1.25.9"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-26137?s=github&n=urllib3&t=pypi&vr=%3C1.25.9"
        }
      ]
    },
    {
      "id": "a3e0e971d20d460fa925b21f7be0adeaa20e0d3d82e44ea13ff89a938b9953e5",
      "category": "container_scanning",
      "message": "CVE-2020-28493 on jinja2@2.10.1",
      "description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDOS vulnerability of the regex is mainly due to the sub-pattern [a-zA-Z0-9._-]+.[a-zA-Z0-9._-]+ This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
      "cve": "CVE-2020-28493",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.10.1 to 2.11.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.10.1"
          },
          "version": "2.10.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28493",
          "value": "CVE-2020-28493",
          "url": "https://scout.docker.com/v/CVE-2020-28493?s=github&n=jinja2&t=pypi&vr=%3C2.11.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28493?s=github&n=jinja2&t=pypi&vr=%3C2.11.3"
        }
      ]
    },
    {
      "id": "3f9a29a44bbce66fd64ce2b6723bac969ac05ea4ac2e09982ffb54e3a95f4a21",
      "category": "container_scanning",
      "message": "CVE-2023-23931 on cryptography@2.6.1",
      "description": "Previously, `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers:\n\n```pycon\n>>> outbuf = b\"\\x00\" * 32\n>>> c = ciphers.Cipher(AES(b\"\\x00\" * 32), modes.ECB()).encryptor()\n>>> c.update_into(b\"\\x00\" * 16, outbuf)\n16\n>>> outbuf\nb'\\xdc\\x95\\xc0x\\xa2@\\x89\\x89\\xadH\\xa2\\x14\\x92\\x84 \\x87\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'\n```\n\nThis would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python. This is a soundness bug -- it allows programmers to misuse an API, it cannot be exploited by attacker controlled data alone.\n\nThis now correctly raises an exception.\n\nThis issue has been present since `update_into` was originally introduced in cryptography 1.8.",
      "cve": "CVE-2023-23931",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 39.0.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-23931",
          "value": "CVE-2023-23931",
          "url": "https://scout.docker.com/v/CVE-2023-23931?s=github&n=cryptography&t=pypi&vr=%3E%3D1.8%2C%3C39.0.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-23931?s=github&n=cryptography&t=pypi&vr=%3E%3D1.8%2C%3C39.0.1"
        }
      ]
    },
    {
      "id": "ec9c4d2413303a57d59811cb792601bb76816a5db8de4b7f4f5291bdab099f9e",
      "category": "container_scanning",
      "message": "CVE-2024-3651 on idna@2.8",
      "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
      "cve": "CVE-2024-3651",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade idna@2.8 to 3.7",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/idna@2.8"
          },
          "version": "2.8"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-3651",
          "value": "CVE-2024-3651",
          "url": "https://scout.docker.com/v/CVE-2024-3651?s=github&n=idna&t=pypi&vr=%3C3.7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-3651?s=github&n=idna&t=pypi&vr=%3C3.7"
        }
      ]
    },
    {
      "id": "5a5701a39cb118455cca120db19e8901903887580cb12915f06eba106ed216a5",
      "category": "container_scanning",
      "message": "CVE-2020-13630 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-13630",
      "severity": "High",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-13630",
          "value": "CVE-2020-13630",
          "url": "https://scout.docker.com/v/CVE-2020-13630?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-13630?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "2f6629814e71f0c4f4df205a87d6753186987fee39fda28335484c2774f93ab4",
      "category": "container_scanning",
      "message": "CVE-2020-11652 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 2019.2.4 and 3000 before 3000.2. The salt-master process ClearFuncs class allows access to some methods that improperly sanitize paths. These methods allow arbitrary directory access to authenticated users.",
      "cve": "CVE-2020-11652",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11652",
          "value": "CVE-2020-11652",
          "url": "https://scout.docker.com/v/CVE-2020-11652?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11652?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ]
    },
    {
      "id": "15ee9d987ed36f5222e1c8bcc6c98e96059042c3dd9bd7bbf214fd1478f5f5d6",
      "category": "container_scanning",
      "message": "CVE-2021-3572 on pip@19.0.3",
      "description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
      "cve": "CVE-2021-3572",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pip@19.0.3 to 21.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@19.0.3"
          },
          "version": "19.0.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3572",
          "value": "CVE-2021-3572",
          "url": "https://scout.docker.com/v/CVE-2021-3572?s=github&n=pip&t=pypi&vr=%3C21.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3572?s=github&n=pip&t=pypi&vr=%3C21.1"
        }
      ]
    },
    {
      "id": "43c0aa2d5d5fc4a07a87b2dd537df9790f63c30bf67a5292dfbc01fde66c58ba",
      "category": "container_scanning",
      "message": "CVE-2023-52323 on pycryptodomex@3.9.0",
      "description": "PyCryptodome and pycryptodomex before 3.19.1 allow side-channel leakage for OAEP decryption, exploitable for a Manger attack.",
      "cve": "CVE-2023-52323",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pycryptodomex@3.9.0 to 3.19.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pycryptodomex@3.9.0"
          },
          "version": "3.9.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-52323",
          "value": "CVE-2023-52323",
          "url": "https://scout.docker.com/v/CVE-2023-52323?s=github&n=pycryptodomex&t=pypi&vr=%3C3.19.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-52323?s=github&n=pycryptodomex&t=pypi&vr=%3C3.19.1"
        }
      ]
    },
    {
      "id": "815d6793c2bf9a3ab4de165b9a638eb4c0d23c986526e119c1f11f08b70d5a2b",
      "category": "container_scanning",
      "message": "CVE-2020-35662 on salt@2019.2.0",
      "description": "In SaltStack Salt before 3002.5, when authenticating to services using certain modules, the SSL certificate is not always validated.",
      "cve": "CVE-2020-35662",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35662",
          "value": "CVE-2020-35662",
          "url": "https://scout.docker.com/v/CVE-2020-35662?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35662?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "e39ade8b0805dcc224dc9a9c289387fa891f2ecb5addba12ace7f75f44861d79",
      "category": "container_scanning",
      "message": "CVE-2021-3450 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2021-3450",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1k-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3450",
          "value": "CVE-2021-3450",
          "url": "https://scout.docker.com/v/CVE-2021-3450?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1k-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3450?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1k-r0"
        }
      ]
    },
    {
      "id": "4340ed9d4d064ad89a05948eb558699b8bdde033266ef49032597547107b93ce",
      "category": "container_scanning",
      "message": "CVE-2023-0286 on cryptography@2.6.1",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8.1-39.0.0  are vulnerable to a security issue. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20221213.txt and https://www.openssl.org/news/secadv/20230207.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "CVE-2023-0286",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 39.0.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-0286",
          "value": "CVE-2023-0286",
          "url": "https://scout.docker.com/v/CVE-2023-0286?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8.1%2C%3C39.0.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-0286?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8.1%2C%3C39.0.1"
        }
      ]
    },
    {
      "id": "2b27cb498d80112e9fcf1e6299a7a014d04462c39cd0ae2ecee8b27778e55c88",
      "category": "container_scanning",
      "message": "CVE-2023-43804 on urllib3@1.25.6",
      "description": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
      "cve": "CVE-2023-43804",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.26.17",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-43804",
          "value": "CVE-2023-43804",
          "url": "https://scout.docker.com/v/CVE-2023-43804?s=github&n=urllib3&t=pypi&vr=%3C1.26.17"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-43804?s=github&n=urllib3&t=pypi&vr=%3C1.26.17"
        }
      ]
    },
    {
      "id": "01fc69e132d2f5652c67e49ed484a22e6f889c68025ebbc5d78228413e46c961",
      "category": "container_scanning",
      "message": "CVE-2019-16056 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2019-16056",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.5-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-16056",
          "value": "CVE-2019-16056",
          "url": "https://scout.docker.com/v/CVE-2019-16056?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.5-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-16056?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.5-r0"
        }
      ]
    },
    {
      "id": "a918842e4dfe1c528ac14dccaf2a7ad857939530aba142349fa8fe2fd2f5f092",
      "category": "container_scanning",
      "message": "CVE-2019-19244 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2019-19244",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/sqlite@3.28.0-r0 to 3.28.0-r2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-19244",
          "value": "CVE-2019-19244",
          "url": "https://scout.docker.com/v/CVE-2019-19244?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-19244?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r2"
        }
      ]
    },
    {
      "id": "f7ecac52348cc0574dfcd33035d68cce81b7ec94c8f1e8c0ada4076727838529",
      "category": "container_scanning",
      "message": "CVE-2020-11655 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-11655",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/sqlite@3.28.0-r0 to 3.28.0-r3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11655",
          "value": "CVE-2020-11655",
          "url": "https://scout.docker.com/v/CVE-2020-11655?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11655?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.28.0-r3"
        }
      ]
    },
    {
      "id": "a35fc15f57a32f0d5b9afa7efb88f972850cd52bac33eefa70708c0cbf7ae98c",
      "category": "container_scanning",
      "message": "CVE-2020-12723 on alpine/perl@5.28.2-r1",
      "cve": "CVE-2020-12723",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/perl@5.28.2-r1 to 5.28.3-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/perl@5.28.2-r1?os_name=alpine&os_version=3.10"
          },
          "version": "5.28.2-r1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-12723",
          "value": "CVE-2020-12723",
          "url": "https://scout.docker.com/v/CVE-2020-12723?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-12723?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ]
    },
    {
      "id": "37e606f5b2b17e553a0339a81b12dd5b50838b964771de2b890f0377fc296964",
      "category": "container_scanning",
      "message": "CVE-2020-1967 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2020-1967",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1g-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-1967",
          "value": "CVE-2020-1967",
          "url": "https://scout.docker.com/v/CVE-2020-1967?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1g-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-1967?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1g-r0"
        }
      ]
    },
    {
      "id": "f0d3214d0716ed74068a8648c58163d8506f5806bf394cf9f66a16c83c6eb0cd",
      "category": "container_scanning",
      "message": "CVE-2021-21996 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 3003.3. A user who has control of the source, and source_hash URLs can gain full file system access as root on a salt minion.",
      "cve": "CVE-2021-21996",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3003.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-21996",
          "value": "CVE-2021-21996",
          "url": "https://scout.docker.com/v/CVE-2021-21996?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-21996?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ]
    },
    {
      "id": "1fc8c537f3d87429dea95158d7ea81471331629657cc992d54a76f34d6ca0e3c",
      "category": "container_scanning",
      "message": "CVE-2021-22004 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 3003.3. The salt minion installer will accept and use a minion config file at C:\\salt\\conf if that file is in place before the installer is run. This allows for a malicious actor to subvert the proper behaviour of the given minion software.",
      "cve": "CVE-2021-22004",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3003.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-22004",
          "value": "CVE-2021-22004",
          "url": "https://scout.docker.com/v/CVE-2021-22004?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-22004?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ]
    },
    {
      "id": "199f6f0ff7c2c4326a24387b66769d46abe66eebb246bd799fc11db4f8c6b0e5",
      "category": "container_scanning",
      "message": "CVE-2021-23840 on alpine/openssl@1.1.1d-r0",
      "cve": "CVE-2021-23840",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/openssl@1.1.1d-r0 to 1.1.1j-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/openssl@1.1.1d-r0?os_name=alpine&os_version=3.10"
          },
          "version": "1.1.1d-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-23840",
          "value": "CVE-2021-23840",
          "url": "https://scout.docker.com/v/CVE-2021-23840?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-23840?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.1.1j-r0"
        }
      ]
    },
    {
      "id": "3bb827ec7734a433f74a760b152b1617bf22697f4c9b833cbd65442241a7ce26",
      "category": "container_scanning",
      "message": "CVE-2021-28831 on alpine/busybox@1.30.1-r2",
      "cve": "CVE-2021-28831",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/busybox@1.30.1-r2 to 1.30.1-r5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/busybox@1.30.1-r2?os_name=alpine&os_version=3.10"
          },
          "version": "1.30.1-r2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-28831",
          "value": "CVE-2021-28831",
          "url": "https://scout.docker.com/v/CVE-2021-28831?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.30.1-r5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-28831?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C1.30.1-r5"
        }
      ]
    },
    {
      "id": "14e44070abeafc9a293cded04967d3d65f789cfe191b8fd8f8e8b9e864ec44c6",
      "category": "container_scanning",
      "message": "CVE-2021-30139 on alpine/apk-tools@2.10.4-r2",
      "cve": "CVE-2021-30139",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/apk-tools@2.10.4-r2 to 2.10.6-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/apk-tools@2.10.4-r2?os_name=alpine&os_version=3.10"
          },
          "version": "2.10.4-r2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-30139",
          "value": "CVE-2021-30139",
          "url": "https://scout.docker.com/v/CVE-2021-30139?s=alpine&n=apk-tools&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.10.6-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-30139?s=alpine&n=apk-tools&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.10.6-r0"
        }
      ]
    },
    {
      "id": "a20e51a644dd18ede0c764c6334c27db9707cb26ccde4bbd5b4d622be2bd12f7",
      "category": "container_scanning",
      "message": "CVE-2023-37920 on certifi@2019.9.11",
      "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
      "cve": "CVE-2023-37920",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade certifi@2019.9.11 to 2023.7.22",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/certifi@2019.9.11"
          },
          "version": "2019.9.11"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-37920",
          "value": "CVE-2023-37920",
          "url": "https://scout.docker.com/v/CVE-2023-37920?s=github&n=certifi&t=pypi&vr=%3E%3D2015.4.28%2C%3C2023.7.22"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-37920?s=github&n=certifi&t=pypi&vr=%3E%3D2015.4.28%2C%3C2023.7.22"
        }
      ]
    },
    {
      "id": "8a471a4a61390d1bf30d1d67b3ee03e1d4d6bae3063ad6777549c3ae2640a83d",
      "category": "container_scanning",
      "message": "CVE-2024-52804 on tornado@4.5.3",
      "description": "The algorithm used for parsing HTTP cookies in Tornado versions prior to 6.4.2 sometimes has quadratic complexity, leading to excessive CPU consumption when parsing maliciously-crafted cookie headers. This parsing occurs in the event loop thread and may block the processing of other requests.\n\nSee also CVE-2024-7592 for a similar vulnerability in cpython.",
      "cve": "CVE-2024-52804",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.4.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-52804",
          "value": "CVE-2024-52804",
          "url": "https://scout.docker.com/v/CVE-2024-52804?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-52804?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.1"
        }
      ]
    },
    {
      "id": "8b8335559516672a4b326c84df4309d4c1e774ffeffed4f888e768c71b7cf350",
      "category": "container_scanning",
      "message": "CVE-2024-6345 on setuptools@40.8.0",
      "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
      "cve": "CVE-2024-6345",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@40.8.0 to 70.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@40.8.0"
          },
          "version": "40.8.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-6345",
          "value": "CVE-2024-6345",
          "url": "https://scout.docker.com/v/CVE-2024-6345?s=github&n=setuptools&t=pypi&vr=%3C70.0.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-6345?s=github&n=setuptools&t=pypi&vr=%3C70.0.0"
        }
      ]
    },
    {
      "id": "df75a03c469019e09189df9aec85f09f556b58c2b39cf18e7bb0f516c95f3233",
      "category": "container_scanning",
      "message": "CVE-2025-47287 on tornado@4.5.3",
      "description": "### Summary\n\nWhen Tornado's ``multipart/form-data`` parser encounters certain errors, it logs a warning but continues trying to parse the remainder of the data. This allows remote attackers to generate an extremely high volume of logs, constituting a DoS attack. This DoS is compounded by the fact that the logging subsystem is synchronous.\n\n### Affected versions\n\nAll versions of Tornado prior to 6.5 are affected. The vulnerable parser is enabled by default.\n\n### Solution\n\nUpgrade to Tornado version 6.5. In the meantime, risk can be mitigated by blocking `Content-Type: multipart/form-data` in a proxy.",
      "cve": "CVE-2025-47287",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@4.5.3 to 6.5.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@4.5.3"
          },
          "version": "4.5.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-47287",
          "value": "CVE-2025-47287",
          "url": "https://scout.docker.com/v/CVE-2025-47287?s=github&n=tornado&t=pypi&vr=%3C6.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-47287?s=github&n=tornado&t=pypi&vr=%3C6.5"
        }
      ]
    },
    {
      "id": "1c09a28991dc18a96e6b7ec2d02dfb4e7398184c3e25fd9c5b8e4c373a79595e",
      "category": "container_scanning",
      "message": "CVE-2022-22967 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.9, 3003.5, 3004.2. PAM auth fails to reject locked accounts, which allows a previously authorized user whose account is locked still run Salt commands when their account is locked. This affects both local shell accounts with an active session and salt-api users that authenticate via PAM eauth.",
      "cve": "CVE-2022-22967",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.9",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22967",
          "value": "CVE-2022-22967",
          "url": "https://scout.docker.com/v/CVE-2022-22967?s=github&n=salt&t=pypi&vr=%3C3002.9"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22967?s=github&n=salt&t=pypi&vr=%3C3002.9"
        }
      ]
    },
    {
      "id": "fcc5202a7e26ee637a822f6da5011d53710b3fc78286f2be0222f8b02f441979",
      "category": "container_scanning",
      "message": "CVE-2024-22232 on salt@2019.2.0",
      "description": "A specially crafted url can be created which leads to a directory traversal in the salt file server.\nA malicious user can read an arbitrary file from a Salt master’s filesystem.",
      "cve": "CVE-2024-22232",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3005.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22232",
          "value": "CVE-2024-22232",
          "url": "https://scout.docker.com/v/CVE-2024-22232?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22232?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ]
    },
    {
      "id": "628412165473b6fd4fc10e650bf508c648ddfea75ef7fa38d4cf03c5022ffefd",
      "category": "container_scanning",
      "message": "CVE-2025-47273 on setuptools@40.8.0",
      "description": "### Summary \nA path traversal vulnerability in `PackageIndex` was fixed in setuptools version 78.1.1\n\n### Details\n```\n    def _download_url(self, url, tmpdir):\n        # Determine download filename\n        #\n        name, _fragment = egg_info_for_url(url)\n        if name:\n            while '..' in name:\n                name = name.replace('..', '.').replace('\\\\', '_')\n        else:\n            name = \"__downloaded__\"  # default if URL has no path contents\n\n        if name.endswith('.[egg.zip](http://egg.zip/)'):\n            name = name[:-4]  # strip the extra .zip before download\n\n -->       filename = os.path.join(tmpdir, name)\n```\n\nHere: https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88\n\n`os.path.join()` discards the first argument `tmpdir` if the second begins with a slash or drive letter.\n`name` is derived from a URL without sufficient sanitization. While there is some attempt to sanitize by replacing instances of '..' with '.', it is insufficient.\n\n### Risk Assessment\nAs easy_install and package_index are deprecated, the exploitation surface is reduced.\nHowever, it seems this could be exploited in a similar fashion like https://github.com/advisories/GHSA-r9hx-vwmv-q579, and as described by POC 4 in https://github.com/advisories/GHSA-cx63-2mw6-8hw5 report: via malicious URLs present on the pages of a package index.\n\n### Impact\nAn attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to RCE depending on the context.\n\n### References\nhttps://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5\nhttps://github.com/pypa/setuptools/issues/4946",
      "cve": "CVE-2025-47273",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@40.8.0 to 78.1.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@40.8.0"
          },
          "version": "40.8.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-47273",
          "value": "CVE-2025-47273",
          "url": "https://scout.docker.com/v/CVE-2025-47273?s=github&n=setuptools&t=pypi&vr=%3C78.1.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-47273?s=github&n=setuptools&t=pypi&vr=%3C78.1.1"
        }
      ]
    },
    {
      "id": "b84191fcd55cd0f52e976bd6a44597104937053c87ca78d3c78ba89f51c3cfa3",
      "category": "container_scanning",
      "message": "CVE-2020-28243 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. The minion's `restartcheck` is vulnerable to command injection via a crafted process name. This allows for a local privilege escalation by any user able to create a files on the minion in a non-blacklisted directory.",
      "cve": "CVE-2020-28243",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28243",
          "value": "CVE-2020-28243",
          "url": "https://scout.docker.com/v/CVE-2020-28243?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28243?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "f982ae1dad71e6f23738737d396462af372f92300dea1da0d2467de581c08810",
      "category": "container_scanning",
      "message": "CVE-2021-20294 on alpine/binutils@2.32-r0",
      "cve": "CVE-2021-20294",
      "severity": "High",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/binutils@2.32-r0?os_name=alpine&os_version=3.10"
          },
          "version": "2.32-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-20294",
          "value": "CVE-2021-20294",
          "url": "https://scout.docker.com/v/CVE-2021-20294?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-20294?s=alpine&n=binutils&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D2.32-r1"
        }
      ]
    },
    {
      "id": "a8419c0fe68751bd88c2939d5e7ed1b73ad83040c44862e58f9b9ce0436d38bd",
      "category": "container_scanning",
      "message": "CVE-2021-25315 on salt@2019.2.0",
      "description": "A Incorrect Implementation of Authentication Algorithm vulnerability in of SUSE SUSE Linux Enterprise Server 15 SP 3; openSUSE Tumbleweed allows local attackers to execute arbitrary code via salt without the need to specify valid credentials. This issue affects: SUSE SUSE Linux Enterprise Server 15 SP 3 salt versions prior to 3002.2-3. openSUSE Tumbleweed salt version 3002.2-2.1 and prior versions.",
      "cve": "CVE-2021-25315",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25315",
          "value": "CVE-2021-25315",
          "url": "https://scout.docker.com/v/CVE-2021-25315?s=github&n=salt&t=pypi&vr=%3C3002.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25315?s=github&n=salt&t=pypi&vr=%3C3002.2"
        }
      ]
    },
    {
      "id": "1d8926385e60b25f685c6a9a05d94f43b13f3a0bd644bb52465e5a028d4a4359",
      "category": "container_scanning",
      "message": "CVE-2021-31607 on salt@2019.2.0",
      "description": "In SaltStack Salt 2016.9 through 3002.6, a command injection vulnerability exists in the snapper module that allows for local privilege escalation on a minion. The attack requires that a file is created with a pathname that is backed up by snapper, and that the master calls the snapper.diff function (which executes popen unsafely).",
      "cve": "CVE-2021-31607",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3003rc1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-31607",
          "value": "CVE-2021-31607",
          "url": "https://scout.docker.com/v/CVE-2021-31607?s=github&n=salt&t=pypi&vr=%3E%3D2016.11.0%2C%3C%3D3002.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-31607?s=github&n=salt&t=pypi&vr=%3E%3D2016.11.0%2C%3C%3D3002.6"
        }
      ]
    },
    {
      "id": "c2e852f3629166cff380c2e1017983caffe4cd4a0980824ac3bfc1dedf0d9fb0",
      "category": "container_scanning",
      "message": "CVE-2020-10543 on alpine/perl@5.28.2-r1",
      "cve": "CVE-2020-10543",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/perl@5.28.2-r1 to 5.28.3-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/perl@5.28.2-r1?os_name=alpine&os_version=3.10"
          },
          "version": "5.28.2-r1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-10543",
          "value": "CVE-2020-10543",
          "url": "https://scout.docker.com/v/CVE-2020-10543?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-10543?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ]
    },
    {
      "id": "bc43ca78b0d1a9b79eec1c1c600cc7e53669172eca9cc6e46ce17c2d3e9357b9",
      "category": "container_scanning",
      "message": "CVE-2020-25659 on cryptography@2.6.1",
      "description": "RSA decryption was vulnerable to Bleichenbacher timing vulnerabilities, which would impact people using RSA decryption in online scenarios. This is fixed in cryptography 3.2. ",
      "cve": "CVE-2020-25659",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 3.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-25659",
          "value": "CVE-2020-25659",
          "url": "https://scout.docker.com/v/CVE-2020-25659?s=github&n=cryptography&t=pypi&vr=%3C3.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-25659?s=github&n=cryptography&t=pypi&vr=%3C3.2"
        }
      ]
    },
    {
      "id": "0f1e83e5735fd20617d311f221e276372806f1ea3d2509293a6a7b900fb60940",
      "category": "container_scanning",
      "message": "CVE-2020-28972 on salt@2019.2.0",
      "description": "In SaltStack Salt before 3002.5, authentication to VMware vcenter, vsphere, and esxi servers (in the `vmware.py` files) does not always validate the SSL/TLS certificate.",
      "cve": "CVE-2020-28972",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28972",
          "value": "CVE-2020-28972",
          "url": "https://scout.docker.com/v/CVE-2020-28972?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28972?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "fb1d625b1d646614da4dfd2d96f6503fde10e28bea159f95ab1b1556d3cde8af",
      "category": "container_scanning",
      "message": "CVE-2020-10878 on alpine/perl@5.28.2-r1",
      "cve": "CVE-2020-10878",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/perl@5.28.2-r1 to 5.28.3-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/perl@5.28.2-r1?os_name=alpine&os_version=3.10"
          },
          "version": "5.28.2-r1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-10878",
          "value": "CVE-2020-10878",
          "url": "https://scout.docker.com/v/CVE-2020-10878?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-10878?s=alpine&n=perl&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C5.28.3-r0"
        }
      ]
    },
    {
      "id": "8e144da9a112a3da7ab6da934024076fd7d3f637113e464b0179999d851cc84c",
      "category": "container_scanning",
      "message": "CVE-2018-6594 on pycrypto@2.6.1",
      "description": "lib/Crypto/PublicKey/ElGamal.py in PyCrypto through 2.6.1 generates weak ElGamal key parameters, which allows attackers to obtain sensitive information by reading ciphertext data (i.e., it does not have semantic security in face of a ciphertext-only attack). The Decisional Diffie-Hellman (DDH) assumption does not hold for PyCrypto's ElGamal implementation.",
      "cve": "CVE-2018-6594",
      "severity": "High",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pycrypto@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2018-6594",
          "value": "CVE-2018-6594",
          "url": "https://scout.docker.com/v/CVE-2018-6594?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2018-6594?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ]
    },
    {
      "id": "022397ffe187275db5e47cf6087a2f6c22a35bfe9d523b709797bcaddcfc2357",
      "category": "container_scanning",
      "message": "CVE-2019-20916 on pip@19.0.3",
      "description": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py. A fix was committed 6704f2ace.",
      "cve": "CVE-2019-20916",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pip@19.0.3 to 19.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@19.0.3"
          },
          "version": "19.0.3"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-20916",
          "value": "CVE-2019-20916",
          "url": "https://scout.docker.com/v/CVE-2019-20916?s=github&n=pip&t=pypi&vr=%3C19.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-20916?s=github&n=pip&t=pypi&vr=%3C19.2"
        }
      ]
    },
    {
      "id": "646c6915f07e5288b407fb808155a84ffc9e66e7953633e3113610528334d6b2",
      "category": "container_scanning",
      "message": "CVE-2020-7212 on urllib3@1.25.6",
      "description": "The _encode_invalid_chars function in util/url.py in the urllib3 library 1.25.2 through 1.25.7 for Python allows a denial of service (CPU consumption) because of an inefficient algorithm. The percent_encodings array contains all matches of percent encodings. It is not deduplicated. For a URL of length N, the size of percent_encodings may be up to O(N). The next step (normalize existing percent-encoded bytes) also takes up to O(N) for each step, so the total time is O(N^2). If percent_encodings were deduplicated, the time to compute _encode_invalid_chars would be O(kN), where k is at most 484 ((10+6*2)^2).",
      "cve": "CVE-2020-7212",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.25.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-7212",
          "value": "CVE-2020-7212",
          "url": "https://scout.docker.com/v/CVE-2020-7212?s=github&n=urllib3&t=pypi&vr=%3E%3D1.25.2%2C%3C%3D1.25.7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-7212?s=github&n=urllib3&t=pypi&vr=%3E%3D1.25.2%2C%3C%3D1.25.7"
        }
      ]
    },
    {
      "id": "daf28cc05fbe6c985b7c254d5775c6be3bbb5ee1f0b2532eb23fb3ee29d4d249",
      "category": "container_scanning",
      "message": "CVE-2021-33503 on urllib3@1.25.6",
      "description": "### Impact\n\nWhen provided with a URL containing many `@` characters in the authority component the authority regular expression exhibits catastrophic backtracking causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.\n\n\n### Patches\n\nThe issue has been fixed in urllib3 v1.26.5.\n\n### References\n\n- [CVE-2021-33503](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503)\n- [JVNVU#92413403 (English)](https://jvn.jp/en/vu/JVNVU92413403/)\n- [JVNVU#92413403 (Japanese)](https://jvn.jp/vu/JVNVU92413403/)\n- [urllib3 v1.26.5](https://github.com/urllib3/urllib3/releases/tag/1.26.5)\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Ask in our [community Discord](https://discord.gg/urllib3)\n* Email [sethmichaellarson@gmail.com](mailto:sethmichaellarson@gmail.com)\n",
      "cve": "CVE-2021-33503",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.25.6 to 1.26.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.25.6"
          },
          "version": "1.25.6"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-33503",
          "value": "CVE-2021-33503",
          "url": "https://scout.docker.com/v/CVE-2021-33503?s=github&n=urllib3&t=pypi&vr=%3E%3D1.25.4%2C%3C1.26.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-33503?s=github&n=urllib3&t=pypi&vr=%3E%3D1.25.4%2C%3C1.26.5"
        }
      ]
    },
    {
      "id": "ae87fb8142f180b968b81e70526c9bf612e7a1d3382a4c49192f9a93463a741c",
      "category": "container_scanning",
      "message": "CVE-2022-22934 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. Salt Masters do not sign pillar data with the minion’s public key, which can result in attackers substituting arbitrary pillar data.",
      "cve": "CVE-2022-22934",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22934",
          "value": "CVE-2022-22934",
          "url": "https://scout.docker.com/v/CVE-2022-22934?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22934?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "ae6023bcb4b01c5d57fbc6e2eadf9f85dfe53aa3662f8fdeaaab5309b4369647",
      "category": "container_scanning",
      "message": "CVE-2022-40897 on setuptools@40.8.0",
      "description": "Python Packaging Authority (PyPA)'s setuptools is a library designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a vulnerable Regular Expression in `package_index`. This has been patched in version 65.5.1.",
      "cve": "CVE-2022-40897",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@40.8.0 to 65.5.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@40.8.0"
          },
          "version": "40.8.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-40897",
          "value": "CVE-2022-40897",
          "url": "https://scout.docker.com/v/CVE-2022-40897?s=github&n=setuptools&t=pypi&vr=%3C65.5.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-40897?s=github&n=setuptools&t=pypi&vr=%3C65.5.1"
        }
      ]
    },
    {
      "id": "a632b5a245d428a75399c5e44673a69346166c095036d014851425f6eebfc384",
      "category": "container_scanning",
      "message": "CVE-2023-50782 on cryptography@2.6.1",
      "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
      "cve": "CVE-2023-50782",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.6.1 to 42.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-50782",
          "value": "CVE-2023-50782",
          "url": "https://scout.docker.com/v/CVE-2023-50782?s=github&n=cryptography&t=pypi&vr=%3C42.0.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-50782?s=github&n=cryptography&t=pypi&vr=%3C42.0.0"
        }
      ]
    },
    {
      "id": "b6717b302c635a4915d9cddcafa25137b5a1dde22e335ffd798085be1e3e896b",
      "category": "container_scanning",
      "message": "CVE-2021-25282 on salt@2019.2.0",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. The `salt.wheel.pillar_roots.write` method is vulnerable to directory traversal.",
      "cve": "CVE-2021-25282",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25282",
          "value": "CVE-2021-25282",
          "url": "https://scout.docker.com/v/CVE-2021-25282?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25282?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "968e60bb8cbc7c843ac08443ab31574667299770b58c4d5919735b8e4dc73b3b",
      "category": "container_scanning",
      "message": "CVE-2022-22936 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. Job publishes and file server replies are susceptible to replay attacks, which can result in an attacker replaying job publishes causing minions to run old jobs. File server replies can also be re-played. A sufficient craft attacker could gain root access on minion under certain scenarios.",
      "cve": "CVE-2022-22936",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22936",
          "value": "CVE-2022-22936",
          "url": "https://scout.docker.com/v/CVE-2022-22936?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22936?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "1ec0c2e8d65023e1934f6c9bcc1ac1d701616f019188916017186553b8cf2041",
      "category": "container_scanning",
      "message": "CVE-2022-22941 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. When configured as a Master-of-Masters, with a publisher_acl, if a user configured in the publisher_acl targets any minion connected to the Syndic, the Salt Master incorrectly interpreted no valid targets as valid, allowing configured users to target any of the minions connected to the syndic with their configured commands. This requires a syndic master combined with publisher_acl configured on the Master-of-Masters, allowing users specified in the publisher_acl to bypass permissions, publishing authorized commands to any configured minion.",
      "cve": "CVE-2022-22941",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22941",
          "value": "CVE-2022-22941",
          "url": "https://scout.docker.com/v/CVE-2022-22941?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22941?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "942defcd729fd6ce4f49e998b28cb1def4eaa2d5bda6a14cbfe992d58a8ed738",
      "category": "container_scanning",
      "message": "CVE-2021-3144 on salt@2019.2.0",
      "description": "In SaltStack Salt before 3002.5, eauth tokens can be used once after expiration. (They might be used to run command against the salt master or minions.)",
      "cve": "CVE-2021-3144",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3144",
          "value": "CVE-2021-3144",
          "url": "https://scout.docker.com/v/CVE-2021-3144?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3144?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "bd3d3bf1ba5f9f7b581cc67ca7f13c2c332a48c4b7080ee4d156e3b7fbce4094",
      "category": "container_scanning",
      "message": "CVE-2021-36159 on alpine/apk-tools@2.10.4-r2",
      "cve": "CVE-2021-36159",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/apk-tools@2.10.4-r2 to 2.10.7-r0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/apk-tools@2.10.4-r2?os_name=alpine&os_version=3.10"
          },
          "version": "2.10.4-r2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-36159",
          "value": "CVE-2021-36159",
          "url": "https://scout.docker.com/v/CVE-2021-36159?s=alpine&n=apk-tools&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.10.7-r0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-36159?s=alpine&n=apk-tools&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C2.10.7-r0"
        }
      ]
    },
    {
      "id": "86481e8080bcaa918d23e55c729380385d78d259b75d47c165de72c7713abf0c",
      "category": "container_scanning",
      "message": "CVE-2013-7459 on pycrypto@2.6.1",
      "description": "Heap-based buffer overflow in the ALGnew function in block_templace.c in Python Cryptography Toolkit (aka pycrypto) allows remote attackers to execute arbitrary code as demonstrated by a crafted iv parameter to cryptmsg.py.",
      "cve": "CVE-2013-7459",
      "severity": "Critical",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pycrypto@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2013-7459",
          "value": "CVE-2013-7459",
          "url": "https://scout.docker.com/v/CVE-2013-7459?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2013-7459?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ]
    },
    {
      "id": "3fd5e680f1bdd60a66edc6a2adf58f08be707a4e2863c5a10b7539b6ba5c7609",
      "category": "container_scanning",
      "message": "CVE-2019-20477 on pyyaml@5.1.2",
      "description": "PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.",
      "cve": "CVE-2019-20477",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade pyyaml@5.1.2 to 5.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyyaml@5.1.2"
          },
          "version": "5.1.2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-20477",
          "value": "CVE-2019-20477",
          "url": "https://scout.docker.com/v/CVE-2019-20477?s=github&n=pyyaml&t=pypi&vr=%3E%3D5.1%2C%3C5.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-20477?s=github&n=pyyaml&t=pypi&vr=%3E%3D5.1%2C%3C5.2"
        }
      ]
    },
    {
      "id": "77f031d91fd7189a85fe39c5d44540bdce5f93d10f8bb610372e5cfeca44c1a9",
      "category": "container_scanning",
      "message": "CVE-2020-11651 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 2019.2.4 and 3000 before 3000.2. The salt-master process ClearFuncs class does not properly validate method calls. This allows a remote user to access some methods without authentication. These methods can be used to retrieve user tokens from the salt master and/or run arbitrary commands on salt minions.",
      "cve": "CVE-2020-11651",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11651",
          "value": "CVE-2020-11651",
          "url": "https://scout.docker.com/v/CVE-2020-11651?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11651?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ]
    },
    {
      "id": "5442ccb5cd2802355b4085bced081d42df4c22510e77a82798b3875e1a3bb3f5",
      "category": "container_scanning",
      "message": "CVE-2020-14343 on pyyaml@5.1.2",
      "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
      "cve": "CVE-2020-14343",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade pyyaml@5.1.2 to 5.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyyaml@5.1.2"
          },
          "version": "5.1.2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-14343",
          "value": "CVE-2020-14343",
          "url": "https://scout.docker.com/v/CVE-2020-14343?s=github&n=pyyaml&t=pypi&vr=%3C5.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-14343?s=github&n=pyyaml&t=pypi&vr=%3C5.4"
        }
      ]
    },
    {
      "id": "5efeb31f2989472d7df5d79f89ac2e6208472f3ba5115bc27a3734f4e7dcac14",
      "category": "container_scanning",
      "message": "CVE-2020-1747 on pyyaml@5.1.2",
      "description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
      "cve": "CVE-2020-1747",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade pyyaml@5.1.2 to 5.3.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyyaml@5.1.2"
          },
          "version": "5.1.2"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-1747",
          "value": "CVE-2020-1747",
          "url": "https://scout.docker.com/v/CVE-2020-1747?s=github&n=pyyaml&t=pypi&vr=%3E%3D5.1b7%2C%3C5.3.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-1747?s=github&n=pyyaml&t=pypi&vr=%3E%3D5.1b7%2C%3C5.3.1"
        }
      ]
    },
    {
      "id": "c6fb78ed7d95d3dda16ac31f8726238d0fa3114825c49cb21be940d603014a5a",
      "category": "container_scanning",
      "message": "CVE-2019-17361 on salt@2019.2.0",
      "description": "In SaltStack Salt before 2019.2.3, the salt-api NET API with the ssh client enabled is vulnerable to command injection. This allows an unauthenticated attacker with network access to the API endpoint to execute arbitrary code on the salt-api host.",
      "cve": "CVE-2019-17361",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-17361",
          "value": "CVE-2019-17361",
          "url": "https://scout.docker.com/v/CVE-2019-17361?s=github&n=salt&t=pypi&vr=%3C2019.2.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-17361?s=github&n=salt&t=pypi&vr=%3C2019.2.3"
        }
      ]
    },
    {
      "id": "394572899584a6c20f779be62036cb46551017073fea6b110299bbcc534f3321",
      "category": "container_scanning",
      "message": "CVE-2020-11656 on alpine/sqlite@3.28.0-r0",
      "cve": "CVE-2020-11656",
      "severity": "Critical",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/sqlite@3.28.0-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.28.0-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11656",
          "value": "CVE-2020-11656",
          "url": "https://scout.docker.com/v/CVE-2020-11656?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11656?s=alpine&n=sqlite&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C%3D3.28.0-r3"
        }
      ]
    },
    {
      "id": "8aab54685448085feaaa91988ea4d46dd1f49809cc7d9e30be13077eeb142e5f",
      "category": "container_scanning",
      "message": "CVE-2020-16846 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt through 3002. Sending crafted web requests to the Salt API, with the SSH client enabled, can result in shell injection.",
      "cve": "CVE-2020-16846",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-16846",
          "value": "CVE-2020-16846",
          "url": "https://scout.docker.com/v/CVE-2020-16846?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-16846?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ]
    },
    {
      "id": "43dc045c0ce8efe9a3e28767c0351e81232c6dbabcf3faa762f382b4f85b82b9",
      "category": "container_scanning",
      "message": "CVE-2020-25592 on salt@2019.2.0",
      "description": "In SaltStack the salt-netapi improperly validates eauth credentials and tokens. A user can bypass authentication and invoke Salt SSH.",
      "cve": "CVE-2020-25592",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.7",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-25592",
          "value": "CVE-2020-25592",
          "url": "https://scout.docker.com/v/CVE-2020-25592?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-25592?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.7"
        }
      ]
    },
    {
      "id": "37a80274f5be949cee65dcb18c0f380d740ca94d93b6ac4b42aae7664e825fec",
      "category": "container_scanning",
      "message": "CVE-2021-25281 on salt@2019.2.0",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. salt-api does not honor eauth credentials for the wheel_async client. Thus, an attacker can remotely run any wheel modules on the master.",
      "cve": "CVE-2021-25281",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25281",
          "value": "CVE-2021-25281",
          "url": "https://scout.docker.com/v/CVE-2021-25281?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25281?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "4b1c777461263c9f2a8824e8aeefebf3a714e6be270396914f73c38e1d801b84",
      "category": "container_scanning",
      "message": "CVE-2021-25283 on salt@2019.2.0",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. The jinja renderer does not protect against server side template injection attacks.",
      "cve": "CVE-2021-25283",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25283",
          "value": "CVE-2021-25283",
          "url": "https://scout.docker.com/v/CVE-2021-25283?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25283?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "4ddbcfd2c01c93399b8a7ad18ea4c090de534229a430f2db97d66d0a149c1d7c",
      "category": "container_scanning",
      "message": "CVE-2021-3148 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. Sending crafted web requests to the Salt API can result in `salt.utils.thin.gen_thin()` command injection because of different handling of single versus double quotes. This is related to `salt/utils/thin.py`.",
      "cve": "CVE-2021-3148",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3148",
          "value": "CVE-2021-3148",
          "url": "https://scout.docker.com/v/CVE-2021-3148?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3148?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "bc71327daca2cc834c48ca86f09f7d3e30f0b417a939c0bf5141102c31f32e62",
      "category": "container_scanning",
      "message": "CVE-2021-3177 on alpine/python3@3.7.3-r0",
      "cve": "CVE-2021-3177",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade alpine/python3@3.7.3-r0 to 3.7.7-r2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:apk/alpine/python3@3.7.3-r0?os_name=alpine&os_version=3.10"
          },
          "version": "3.7.3-r0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3177",
          "value": "CVE-2021-3177",
          "url": "https://scout.docker.com/v/CVE-2021-3177?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3177?s=alpine&n=python3&ns=alpine&t=apk&osn=alpine&osv=3.10&vr=%3C3.7.7-r2"
        }
      ]
    },
    {
      "id": "705ef89ec35ba1e90d309bef2bbe118a8f0ea91caa1c54e6e4068ac688236e60",
      "category": "container_scanning",
      "message": "CVE-2021-3197 on salt@2019.2.0",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. The salt-api's ssh client is vulnerable to a shell injection by including ProxyCommand in an argument, or via ssh_options provided in an API request.",
      "cve": "CVE-2021-3197",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3197",
          "value": "CVE-2021-3197",
          "url": "https://scout.docker.com/v/CVE-2021-3197?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3197?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "ba68a86c7005c86a04c4db758506b6b5873e2517fd7a703c6aa495aca8c47546",
      "category": "container_scanning",
      "message": "CVE-2021-33226 on salt@2019.2.0",
      "description": "Buffer Overflow vulnerability in Saltstack v.3003 and before allows attacker to execute arbitrary code via the func variable in salt/salt/modules/status.py file.",
      "cve": "CVE-2021-33226",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.0 to 3003.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.0"
          },
          "version": "2019.2.0"
        },
        "operating_system": "alpine 3.10",
        "image": "saltstack/salt:2019.2.0"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-33226",
          "value": "CVE-2021-33226",
          "url": "https://scout.docker.com/v/CVE-2021-33226?s=pypa&n=salt&t=pypi&vr=%3C3003.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-33226?s=pypa&n=salt&t=pypi&vr=%3C3003.1"
        }
      ]
    }
  ],
  "remediations": [],
  "scan": {
    "start_time": "2025-10-17T14:13:30",
    "end_time": "2025-10-17T14:13:30",
    "status": "success",
    "type": "container_scanning",
    "scanner": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    },
    "analyzer": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    }
  }
}
